package cliresult

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"testing"

	"github.com/relux-works/agent-session-manager/internal/axerror"
)

// historicalCorpusDirectory holds the frozen envelopes this package's readers
// must keep reading. They are checked-in bytes rather than objects a test
// builds, because an envelope regenerated by today's writer proves that today's
// writer and today's reader agree - which is a different and much weaker claim
// than the one this corpus exists to make.
const historicalCorpusDirectory = "testdata/historical"

// historicalInvocation is one frozen observation of a completed `ax --json`
// invocation: the exact stdout bytes an older writer produced, the command that
// produced them, and the status the process exited with.
//
// Digest pins the file. Regenerating a fixture to make a test pass is the exact
// failure this corpus is meant to catch, so changing the bytes has to be a
// deliberate act that also moves the digest under review.
type historicalInvocation struct {
	file       string
	digest     string
	release    string
	command    Command
	exitStatus int

	// refusal is the error today's reader must return for these bytes, or nil
	// when the invocation must remain readable.
	refusal error

	// The machine answers a client must still get, for an admitted invocation.
	succeeded      bool
	code           axerror.Code
	codeRegistered bool
	retryable      bool
	detailKeys     []string
}

// historicalCorpus is the reviewed corpus. Each entry names the specification
// release whose writer could have produced the envelope, so an entry is a
// compatibility claim about a published contract version rather than about a
// file someone happened to add.
var historicalCorpus = []historicalInvocation{
	{
		// The Section 14.2 normative CLI success object, verbatim.
		file:       "cli-result-1.0.0-takeover.json",
		digest:     "48c38fa691adcb9e27ffab13a455a6fb8d9912c02816c3347d158c963e7c40b6",
		release:    "v0.1.0",
		command:    CommandTakeover,
		exitStatus: 0,
		succeeded:  true,
	},
	{
		file:       "cli-result-1.0.0-list-empty.json",
		digest:     "78daecfc8c5c289aef9991b2a14f5f7c8fd872c5ac2ba2fd9ce4543602e90374",
		release:    "v0.1.0",
		command:    CommandList,
		exitStatus: 0,
		succeeded:  true,
	},
	{
		// A namespaced extension whose contents this reader knows nothing
		// about. Section 17.2 rule 3 requires it to survive unchanged.
		file:       "cli-result-1.0.0-doctor-extensions.json",
		digest:     "62bbcfee772410cd2d6954f3eeeb40a0713a0dbcb12c2f4409afbd301cd88055",
		release:    "v0.1.0",
		command:    CommandDoctor,
		exitStatus: 0,
		succeeded:  true,
	},
	{
		// The Section 15.1 normative Structured Error object, verbatim.
		file:           "error-1.0.0-workspace-conflict.json",
		digest:         "4861a07c0e6fcdc9437a78781f14bf83ff9eb537e472f8c28a2a7b03a0028d8f",
		release:        "v0.1.0",
		command:        CommandMaterialize,
		exitStatus:     5,
		code:           "workspace_conflict",
		codeRegistered: true,
		detailKeys:     []string{"expected_checkpoint", "remediations"},
	},
	{
		file:           "error-1.0.0-confirmation-required.json",
		digest:         "93276ff95f07cadee19d055a8612b9cc8059a8d90e49f764dc522f87ccf5df49",
		release:        "v0.1.0",
		command:        CommandTakeover,
		exitStatus:     16,
		code:           "confirmation_required",
		codeRegistered: true,
	},
	{
		// Unknown detail keys, which Section 15.1 says a reader "MAY ignore"
		// and must never derive success, authority, or a remediation from.
		file:           "error-1.0.0-partial-sync-unknown-details.json",
		digest:         "9876f13b92d3fad59b69a05544a024c2395848527c335e44e74861251d8e1205",
		release:        "v0.1.0",
		command:        CommandSync,
		exitStatus:     15,
		code:           "partial_sync",
		codeRegistered: true,
		retryable:      true,
		detailKeys:     []string{"future_reader_hint", "remediation", "unreachable_peer_ids"},
	},
	{
		// A code a later compatible minor added, inside the envelope version
		// this command binds. Section 15.3: "an unknown code retains the
		// envelope's exit class and MUST NOT be interpreted as success".
		file:           "error-1.0.0-later-minor-code.json",
		digest:         "aa5d0bcd0a59f1be7b60067e9744088606ed3e94d578e22e08711e52fac9a617",
		release:        "v0.5.0",
		command:        CommandStatus,
		exitStatus:     10,
		code:           "terminal_backend_stale_generation",
		codeRegistered: false,
		detailKeys:     []string{"tmux_server_generation"},
	},
	{
		// The same envelope with retryable forged to true. The class-level
		// refusal still applies to a code this envelope version does not
		// register, so an unreadable code is not a way past the retry rule.
		file:       "error-1.0.0-later-minor-code-forged-retry.json",
		digest:     "f7514a9c5ab163edf1f6e4992cddd1e464fb4eb2235d20bea387b0b22d90c045",
		release:    "v0.5.0",
		command:    CommandStatus,
		exitStatus: 10,
		refusal:    axerror.ErrInvalidStructuredError,
	},
	{
		// The other CLI error binding: session.clone.* selects Structured
		// Error 1.1.0, whose success body this repository does not build.
		file:           "error-1.1.0-source-not-found.json",
		digest:         "50d0c3c522cf7594c80579186c551b43d399bcd39553f6b9b75f7e2e121e97eb",
		release:        "v0.3.0",
		command:        CommandCloneRun,
		exitStatus:     4,
		code:           "source_not_found",
		codeRegistered: true,
		detailKeys:     []string{"requested"},
	},
}

// historicalEntry looks a reviewed entry up by file name. Indexing the corpus
// positionally would bind a test to the order of the table rather than to the
// envelope it means.
func historicalEntry(t *testing.T, file string) historicalInvocation {
	t.Helper()
	for _, candidate := range historicalCorpus {
		if candidate.file == file {
			return candidate
		}
	}
	t.Fatalf("no reviewed corpus entry named %q", file)
	return historicalInvocation{}
}

func readHistorical(t *testing.T, entry historicalInvocation) []byte {
	t.Helper()
	bytes, err := os.ReadFile(filepath.Join(historicalCorpusDirectory, entry.file))
	if err != nil {
		t.Fatalf("read %q: %v", entry.file, err)
	}
	digest := sha256.Sum256(bytes)
	if got := hex.EncodeToString(digest[:]); got != entry.digest {
		t.Fatalf("%q digest = %s, want the reviewed %s; a historical envelope is frozen bytes, "+
			"so regenerating it is a change to the compatibility claim", entry.file, got, entry.digest)
	}
	return bytes
}

// TestHistoricalCorpusIsFrozenAndComplete keeps the corpus honest in both
// directions: every reviewed entry exists with its reviewed bytes, and every
// file in the directory is a reviewed entry. A fixture added without a review
// row would otherwise sit there unread while the suite stayed green.
func TestHistoricalCorpusIsFrozenAndComplete(t *testing.T) {
	t.Parallel()

	entries, err := os.ReadDir(historicalCorpusDirectory)
	if err != nil {
		t.Fatalf("read corpus directory: %v", err)
	}
	var found []string
	for _, entry := range entries {
		found = append(found, entry.Name())
	}
	var reviewed []string
	for _, entry := range historicalCorpus {
		reviewed = append(reviewed, entry.file)
		readHistorical(t, entry)
	}
	sort.Strings(found)
	sort.Strings(reviewed)
	if !reflect.DeepEqual(found, reviewed) {
		t.Fatalf("corpus files %v, reviewed entries %v", found, reviewed)
	}
	if len(reviewed) != 9 {
		t.Fatalf("corpus holds %d envelopes, want the reviewed 9", len(reviewed))
	}
}

// TestHistoricalEnvelopesRemainReadable is the compatibility claim itself.
// Every frozen envelope is classified by today's production reading entry
// point, and every machine answer is the one the reviewed row records.
func TestHistoricalEnvelopesRemainReadable(t *testing.T) {
	t.Parallel()

	for _, entry := range historicalCorpus {
		t.Run(entry.file, func(t *testing.T) {
			document := readHistorical(t, entry)
			reading, err := Read(entry.command, InvocationOutput{Stdout: document, ExitStatus: entry.exitStatus})
			if entry.refusal != nil {
				if !errors.Is(err, entry.refusal) {
					t.Fatalf("Read(%s) error = %v, want %v", entry.file, err, entry.refusal)
				}
				return
			}
			if err != nil {
				t.Fatalf("Read(%s) error = %v, want a readable %s envelope", entry.file, err, entry.release)
			}
			if reading.Succeeded() != entry.succeeded {
				t.Fatalf("Succeeded() = %t, want %t", reading.Succeeded(), entry.succeeded)
			}
			if reading.ExitStatus() != entry.exitStatus {
				t.Fatalf("ExitStatus() = %d, want %d", reading.ExitStatus(), entry.exitStatus)
			}
			code, present := reading.Code()
			if present != !entry.succeeded || code != entry.code {
				t.Fatalf("Code() = %q/%t, want %q/%t", code, present, entry.code, !entry.succeeded)
			}
			if reading.CodeRegistered() != entry.codeRegistered {
				t.Fatalf("CodeRegistered() = %t, want %t", reading.CodeRegistered(), entry.codeRegistered)
			}
			if reading.Retryable() != entry.retryable {
				t.Fatalf("Retryable() = %t, want %t", reading.Retryable(), entry.retryable)
			}
			if entry.succeeded {
				return
			}
			keys := reading.Failure().DetailKeys()
			if len(keys) == 0 {
				keys = nil
			}
			if !reflect.DeepEqual(keys, entry.detailKeys) {
				t.Fatalf("DetailKeys() = %v, want %v", keys, entry.detailKeys)
			}
		})
	}
}

// TestHistoricalFailuresAreClassifiedWithoutTheirMessages replays the whole
// corpus with every human message replaced. A machine answer that moved would
// mean automation was branching on message text, which Section 15.1 forbids:
// "messages are for humans; automation MUST branch on code and exit_code".
func TestHistoricalFailuresAreClassifiedWithoutTheirMessages(t *testing.T) {
	t.Parallel()

	const replacement = "this text says nothing a machine may use"
	classified := 0
	for _, entry := range historicalCorpus {
		if entry.refusal != nil || entry.succeeded {
			continue
		}
		t.Run(entry.file, func(t *testing.T) {
			document := readHistorical(t, entry)
			output := InvocationOutput{Stdout: document, ExitStatus: entry.exitStatus}
			baseline, err := Read(entry.command, output)
			if err != nil {
				t.Fatalf("Read(baseline): %v", err)
			}
			rewritten := rewriteFailure(t, document, map[string]any{"message": replacement})
			if string(rewritten) == string(document) {
				t.Fatal("the rewritten envelope is byte-identical, so this row proves nothing")
			}
			blinded, err := Read(entry.command, InvocationOutput{Stdout: rewritten, ExitStatus: entry.exitStatus})
			if err != nil {
				t.Fatalf("Read(message replaced): %v", err)
			}
			assertSameMachineFacts(t, baseline, blinded)
			if blinded.HumanMessage() == baseline.HumanMessage() {
				t.Fatal("the message did not change, so message-independence was not exercised")
			}
		})
		classified++
	}
	if classified != 5 {
		t.Fatalf("replayed %d failure envelopes, want the reviewed 5", classified)
	}
}

// TestHistoricalExtensionsSurviveAsInertData is Section 17.2 rule 3 over frozen
// bytes: an extension namespace this reader knows nothing about is preserved
// when the object is forwarded, and nothing about the outcome is derived from
// it.
func TestHistoricalExtensionsSurviveAsInertData(t *testing.T) {
	t.Parallel()

	const file = "cli-result-1.0.0-doctor-extensions.json"
	entry := historicalEntry(t, file)
	document := readHistorical(t, entry)
	reading, err := Read(entry.command, InvocationOutput{Stdout: document, ExitStatus: entry.exitStatus})
	if err != nil {
		t.Fatalf("Read(%s): %v", file, err)
	}

	var original map[string]any
	if err := json.Unmarshal(document, &original); err != nil {
		t.Fatalf("decode original: %v", err)
	}
	wantExtensions := original["extensions"].(map[string]any)
	if len(wantExtensions) == 0 {
		t.Fatal("the fixture carries no extension, so this test proves nothing")
	}

	forwarded, err := reading.Result().MarshalJSON()
	if err != nil {
		t.Fatalf("MarshalJSON: %v", err)
	}
	var round map[string]any
	if err := json.Unmarshal(forwarded, &round); err != nil {
		t.Fatalf("decode forwarded: %v", err)
	}
	if !reflect.DeepEqual(round["extensions"], wantExtensions) {
		t.Fatalf("forwarded extensions = %v, want %v", round["extensions"], wantExtensions)
	}
	if _, known := reading.Result().Extension("works.relux.ax.future-reader-hint"); !known {
		t.Fatal("the unknown namespace was dropped rather than retained")
	}
	if !reading.Succeeded() {
		t.Fatal("an inert extension changed the outcome")
	}
}
