#!/usr/bin/env python3
"""Narrowing-mutant harness for internal/terminstance.

Every gate ships a narrowing mutant: the gate stays present and is
weakened to admit exactly one member of the class it must reject, and
the named killer test must fail. A delete-only mutant proves only that
the gate exists and is not accepted as evidence.

Each row runs M (mutate one production file in place), R (run the
scoped Go killer through the production entry point), V (verdict from
the Go exit code plus a FAIL kill-line: KILLED iff R fails with a test
failure line, SURVIVED iff R passes, ERROR for anything else —
unapplied patches, build breaks, timeouts). M failures and R
infrastructure errors are ERROR, never kills or survivals. The file is
restored from its backup after every row, pass or fail.

Row C-control is the harmless control: a comment-only edit that
must SURVIVE, proving the harness observes test outcomes instead of
hard-coding kills.

Usage:
  PYTHONDONTWRITEBYTECODE=1 python3 internal/terminstance/mutant_harness.py
  PYTHONDONTWRITEBYTECODE=1 python3 internal/terminstance/mutant_harness.py N-auth-epoch-low
"""

import os
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
PACKAGE = "internal/terminstance"


@dataclass(frozen=True)
class Mutant:
    name: str
    path: str
    find: str
    replace: str
    count: int
    run: str
    expect: str
    note: str
    find2: str = ""
    replace2: str = ""
    count2: int = 0


MUTANTS = [
    Mutant(
        name="N-auth-epoch-low",
        path=f"{PACKAGE}/auth.go",
        find='\tleaseEpoch, ok := environ.CheckUint53Bounds(members["lease_epoch"], 1, MaxLeaseEpoch)\n',
        replace='\tleaseEpoch, ok := environ.CheckUint53Bounds(members["lease_epoch"], 0, MaxLeaseEpoch)\n',
        count=1,
        run="TestParseAXAuthorizationEpochBound",
        expect="KILLED",
        note="Admits exactly epoch 0; every other out-of-range epoch still refuses.",
    ),
    Mutant(
        name="N-auth-epoch-high",
        path=f"{PACKAGE}/auth.go",
        find='\tleaseEpoch, ok := environ.CheckUint53Bounds(members["lease_epoch"], 1, MaxLeaseEpoch)\n',
        replace='\tleaseEpoch, ok := environ.CheckUint53Bounds(members["lease_epoch"], 1, MaxLeaseEpoch-1)\n',
        count=1,
        run="TestParseAXAuthorizationEpochBound",
        expect="KILLED",
        note="TIGHTENING (the weakening direction is equivalent: environ refuses 2^53 at the number layer, so no weakening past MaxLeaseEpoch is observable; this row proves the edge is exactly 9007199254740991 by refusing it).",
    ),
    Mutant(
        name="N-auth-kind",
        path=f"{PACKAGE}/auth.go",
        find='\tdefault:\n\t\treturn "", refuse(CodeProtocolError, "ax authorization kind")\n\t}\n',
        replace='\tdefault:\n\t\tif value == "admin" {\n\t\t\treturn AuthorizationControl, nil\n\t\t}\n\t\treturn "", refuse(CodeProtocolError, "ax authorization kind")\n\t}\n',
        count=1,
        run="TestParseAXAuthorizationKindClosed",
        expect="KILLED",
        note="Admits exactly the admin kind; every other non-kind still refuses.",
    ),
    Mutant(
        name="N-auth-kind-binding",
        path=f"{PACKAGE}/auth.go",
        find="\tif auth.Kind != wantKind {\n",
        replace="\tif auth.Kind != wantKind && wantKind != AuthorizationCreate {\n",
        count=1,
        run="TestCheckAuthorizationRefusals/kind_mismatch",
        expect="KILLED",
        note="Admits exactly control authorizations presented as create; other mismatches still refuse.",
    ),
    Mutant(
        name="N-auth-expiry",
        path=f"{PACKAGE}/auth.go",
        find="\tif !now.Before(expires) {\n",
        replace="\tif !now.Before(expires) && !now.Equal(expires) {\n",
        count=1,
        run="TestCheckAuthorizationRefusals/expiry_edge_refuses",
        expect="KILLED",
        note="Admits exactly the expiry instant; past-expiry instants still refuse.",
    ),
    Mutant(
        name="N-auth-lease-id",
        path=f"{PACKAGE}/auth.go",
        find="\tif auth.LeaseID != lease.LeaseID {\n",
        replace='\tif auth.LeaseID != lease.LeaseID && lease.LeaseID != "6ba7b810-9dad-41d1-80b4-00c04fd430c8" {\n',
        count=1,
        run="TestCheckAuthorizationRefusals/lease_identity_drift",
        expect="KILLED",
        note="Admits exactly the drifted test lease; other identity drifts still refuse.",
    ),
    Mutant(
        name="N-auth-lease-epoch",
        path=f"{PACKAGE}/auth.go",
        find="\tif auth.LeaseEpoch != lease.Epoch {\n",
        replace="\tif auth.LeaseEpoch != lease.Epoch && lease.Epoch != 2 {\n",
        count=1,
        run="TestCheckAuthorizationRefusals/lease_epoch_drift",
        expect="KILLED",
        note="Admits exactly the epoch-2 drift; other epoch drifts still refuse.",
    ),
    Mutant(
        name="N-auth-extra-member",
        path=f"{PACKAGE}/auth.go",
        find="\tif len(members) != len(axAuthorizationMembers) {\n",
        replace="\tif len(members) != len(axAuthorizationMembers) && len(members) != len(axAuthorizationMembers)+1 {\n",
        count=1,
        run="TestParseAXAuthorizationClosedShape",
        expect="KILLED",
        note="Admits exactly one-extra-member documents; other shapes still refuse.",
    ),
    Mutant(
        name="N-auth-expiry-order",
        path=f"{PACKAGE}/auth.go",
        find="\tif !expires.After(issued) {\n",
        replace="\tif expires.Before(issued) {\n",
        count=1,
        run="TestParseAXAuthorizationStrictExpiry",
        expect="KILLED",
        note="Admits exactly equal issue/expiry instants; inverted instants still refuse.",
    ),
    Mutant(
        name="N-disp-parse",
        path=f"{PACKAGE}/disposition.go",
        find='\tdefault:\n\t\treturn "", refuse(CodeProtocolError, "retry disposition vocabulary")\n\t}\n',
        replace='\tdefault:\n\t\tif value == "retry" {\n\t\t\treturn DispositionReplaySame, nil\n\t\t}\n\t\treturn "", refuse(CodeProtocolError, "retry disposition vocabulary")\n\t}\n',
        count=1,
        run="TestParseRetryDispositionClosed",
        expect="KILLED",
        note="Admits exactly the retry token; every other non-disposition still refuses.",
    ),
    Mutant(
        name="N-disp-unauthorized",
        path=f"{PACKAGE}/disposition.go",
        find="\tcase CodeUnauthorized:\n\t\treturn DispositionNewAuthorization\n",
        replace="\tcase CodeUnauthorized:\n\t\tif committed {\n\t\t\treturn DispositionStatusFirst\n\t\t}\n\t\treturn DispositionNewAuthorization\n",
        count=1,
        run="TestDispositionForMapping",
        expect="KILLED",
        note="Maps exactly committed unauthorized to status_first; uncommitted still maps new_authorization.",
    ),
    Mutant(
        name="N-disp-timeout",
        path=f"{PACKAGE}/disposition.go",
        find="\tcase CodeTimeout, CodeQuiesceTimeout:\n\t\tif committed {\n\t\t\treturn DispositionStatusFirst\n\t\t}\n\t\treturn DispositionReplaySame\n",
        replace="\tcase CodeTimeout, CodeQuiesceTimeout:\n\t\tif committed {\n\t\t\treturn DispositionStatusFirst\n\t\t}\n\t\tif code == CodeQuiesceTimeout {\n\t\t\treturn DispositionStatusFirst\n\t\t}\n\t\treturn DispositionReplaySame\n",
        count=1,
        run="TestDispositionForMapping",
        expect="KILLED",
        note="Maps exactly uncommitted quiesce_timeout to status_first; terminal_backend_timeout still replays.",
    ),
    Mutant(
        name="N-disp-stop",
        path=f"{PACKAGE}/disposition.go",
        find="\tcase CodeStopTimeout, CodeIdempotencyMismatch, CodeStaleGeneration,\n\t\tCodePreconditionFailed, CodeUnavailable:\n",
        replace="\tcase CodeIdempotencyMismatch, CodeStaleGeneration,\n\t\tCodePreconditionFailed, CodeUnavailable:\n",
        count=1,
        run="TestDispositionForMapping",
        expect="KILLED",
        note="Drops exactly stop_timeout from the status-first group; other members still map there.",
    ),
    Mutant(
        name="N-disp-default",
        path=f"{PACKAGE}/disposition.go",
        find="\tdefault:\n\t\tif committed {\n\t\t\treturn DispositionStatusFirst\n\t\t}\n\t\treturn DispositionRequiredOperatorAction\n\t}\n",
        replace="\tdefault:\n\t\tif committed {\n\t\t\treturn DispositionStatusFirst\n\t\t}\n\t\tif code == CodeCapabilityUnproven {\n\t\t\treturn DispositionReplaySame\n\t\t}\n\t\treturn DispositionRequiredOperatorAction\n\t}\n",
        count=1,
        run="TestDispositionForMapping",
        expect="KILLED",
        note="Maps exactly uncommitted capability_unproven to replay_same; the rest still stop automation.",
    ),
    Mutant(
        name="N-proof-vocab",
        path=f"{PACKAGE}/proof.go",
        find='\tdefault:\n\t\treturn "", refuse(CodeProtocolError, "provider proof vocabulary")\n\t}\n',
        replace='\tdefault:\n\t\tif value == "provider_restart" {\n\t\t\treturn ProofProviderQuiescence, nil\n\t\t}\n\t\treturn "", refuse(CodeProtocolError, "provider proof vocabulary")\n\t}\n',
        count=1,
        run="TestParseProviderProofKindClosed",
        expect="KILLED",
        note="Admits exactly the provider_restart token; every other non-kind still refuses.",
    ),
    Mutant(
        name="N-proof-provider",
        path=f"{PACKAGE}/proof.go",
        find="\tcase ProofProviderQuiescence, ProofProviderProcessExit:\n\t\treturn true\n",
        replace="\tcase ProofProviderQuiescence, ProofProviderProcessExit, ProofAXCheckpointBoundary:\n\t\treturn true\n",
        count=1,
        run="TestRequiresProviderObservation",
        expect="KILLED",
        note="Classifies exactly the AX boundary as a provider kind; other classifications stay.",
    ),
    Mutant(
        name="N-context-key",
        path=f"{PACKAGE}/context.go",
        find="\tif context.IdempotencyKey != derived {\n",
        replace="\tif context.IdempotencyKey != derived && len(context.IdempotencyKey) != len(derived) {\n",
        count=1,
        run="TestCheckMutationContextKeyMaterial",
        expect="KILLED",
        note="Admits exactly same-length wrong keys; other material mismatches still refuse.",
    ),
    Mutant(
        name="N-context-generation",
        path=f"{PACKAGE}/context.go",
        find="\tif err := checkGenerationBound(context.BackendGeneration); err != nil {\n",
        replace="\tif err := checkGenerationBound(context.BackendGeneration); err != nil && len(context.BackendGeneration) != 257 {\n",
        count=1,
        run="TestCheckMutationContextGenerationBound",
        expect="KILLED",
        note="Admits exactly the 257-character generation; other bound violations still refuse.",
    ),
    Mutant(
        name="N-wait-timeout-bound",
        path=f"{PACKAGE}/context.go",
        find="\t\tif params.TimeoutMs < 1 || params.TimeoutMs > 3600000 {\n",
        replace="\t\tif params.TimeoutMs < 1 || params.TimeoutMs > 3600001 {\n",
        count=1,
        run="TestCheckMutationContextParams",
        expect="KILLED",
        note="Admits exactly timeout 3600001; other out-of-bound timeouts still refuse.",
    ),
    Mutant(
        name="N-body-key",
        path=f"{PACKAGE}/bodies.go",
        find="\tif err := CheckMutationContext(operation, context, params); err != nil {\n",
        replace="\tif err := CheckMutationContext(operation, context, params); err != nil && operation != terminalbackend.OperationQuiesceInput {\n",
        count=1,
        run="TestParseOperationBodyRefusals",
        expect="KILLED",
        note="Admits exactly quiesce bodies with inconsistent keys; other bodies still refuse.",
    ),
    Mutant(
        name="N-result-operation",
        path=f"{PACKAGE}/result.go",
        find="\tif result.OperationID != context.OperationID {\n",
        replace='\tif result.OperationID != context.OperationID && result.OperationID != "0198f4c8-8e50-7f66-8f70-ccccccccccc2" {\n',
        count=1,
        run="TestCheckResultRepetitionTamper/operation",
        expect="KILLED",
        note="Admits exactly the tampered test operation ID; other operation tampers still refuse.",
    ),
    Mutant(
        name="N-result-session",
        path=f"{PACKAGE}/result.go",
        find="\tif result.SessionID != context.SessionID {\n",
        replace='\tif result.SessionID != context.SessionID && result.SessionID != "0198f4c8-8e50-7f66-8f70-1234567890ac" {\n',
        count=1,
        run="TestCheckResultRepetitionTamper/session",
        expect="KILLED",
        note="Admits exactly the tampered test session; other session tampers still refuse.",
    ),
    Mutant(
        name="N-result-instance",
        path=f"{PACKAGE}/result.go",
        find="\tif result.TerminalInstanceID != context.TerminalInstanceID {\n",
        replace='\tif result.TerminalInstanceID != context.TerminalInstanceID && result.TerminalInstanceID != "0198f4c8-8e50-7f66-8f70-1234567890ac" {\n',
        count=1,
        run="TestCheckResultRepetitionTamper/instance",
        expect="KILLED",
        note="Admits exactly the tampered test instance; other instance tampers still refuse.",
    ),
    Mutant(
        name="N-result-backend",
        path=f"{PACKAGE}/result.go",
        find="\tif result.TerminalBackendID != context.TerminalBackendID {\n",
        replace='\tif result.TerminalBackendID != context.TerminalBackendID && result.TerminalBackendID != "other.backend" {\n',
        count=1,
        run="TestCheckResultRepetitionTamper/backend",
        expect="KILLED",
        note="Admits exactly the tampered test backend; other backend tampers still refuse.",
    ),
    Mutant(
        name="N-result-implementation",
        path=f"{PACKAGE}/result.go",
        find="\tif result.ImplementationVersion != context.ImplementationVersion {\n",
        replace='\tif result.ImplementationVersion != context.ImplementationVersion && result.ImplementationVersion != "9.9.9" {\n',
        count=1,
        run="TestCheckResultRepetitionTamper/implementation",
        expect="KILLED",
        note="Admits exactly the tampered test version; other version tampers still refuse.",
    ),
    Mutant(
        name="N-result-protocol",
        path=f"{PACKAGE}/result.go",
        find="\tif result.ProtocolVersion != context.ProtocolVersion {\n",
        replace='\tif result.ProtocolVersion != context.ProtocolVersion && result.ProtocolVersion != "1.9.9" {\n',
        count=1,
        run="TestCheckResultRepetitionTamper/protocol",
        expect="KILLED",
        note="Admits exactly the tampered test protocol; other protocol tampers still refuse.",
    ),
    Mutant(
        name="N-result-generation",
        path=f"{PACKAGE}/result.go",
        find="\tif result.BackendGeneration != context.BackendGeneration {\n",
        replace='\tif result.BackendGeneration != context.BackendGeneration && result.BackendGeneration != "generation-two" {\n',
        count=1,
        run="TestCheckResultRepetitionTamper/generation",
        expect="KILLED",
        note="Admits exactly the tampered test generation; other generation tampers still refuse.",
    ),
    Mutant(
        name="N-result-before",
        path=f"{PACKAGE}/result.go",
        find="\tif result.Before != source {\n",
        replace="\tif result.Before != source && result.Before != terminalbackend.StateParked {\n",
        count=1,
        run="TestCheckResultRepetitionTamper/before",
        expect="KILLED",
        note="Admits exactly the parked before-state; other before tampers still refuse.",
    ),
    Mutant(
        name="N-result-effects-order",
        path=f"{PACKAGE}/result.go",
        find="\t\tif effects[index-1] > effects[index] {\n",
        replace="\t\tif effects[index-1] > effects[index] && effects[index-1] != terminalbackend.EffectWrapperStarted {\n",
        count=1,
        run="TestCheckResultShapeArms",
        expect="KILLED",
        note="Admits exactly the wrapper-before-binding inversion; other order violations still refuse.",
    ),
    Mutant(
        name="N-result-evidence-unique",
        path=f"{PACKAGE}/result.go",
        find="\t\tif evidence[index-1] == evidence[index] {\n",
        replace='\t\tif evidence[index-1] == evidence[index] && evidence[index] != "sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa" {\n',
        count=1,
        run="TestCheckResultShapeArms",
        expect="KILLED",
        note="Admits exactly the duplicated fixture digest; other duplicates still refuse.",
    ),
    Mutant(
        name="N-store-mismatch-op",
        path=f"{PACKAGE}/store.go",
        find="\t\t\tif winner.Operation != operation || winner.OperationID != operationID {\n",
        replace="\t\t\tif winner.OperationID != operationID {\n",
        count=1,
        run="TestStoreBindReplayMismatch",
        expect="KILLED",
        note="Admits exactly changed-operation replays as replays; changed IDs still mismatch.",
    ),
    Mutant(
        name="N-store-mismatch-id",
        path=f"{PACKAGE}/store.go",
        find="\t\t\tif winner.Operation != operation || winner.OperationID != operationID {\n",
        replace="\t\t\tif winner.Operation != operation {\n",
        count=1,
        run="TestStoreBindReplayMismatch",
        expect="KILLED",
        note="Admits exactly changed-ID replays as replays; changed operations still mismatch.",
    ),
    Mutant(
        name="N-store-replay",
        path=f"{PACKAGE}/store.go",
        find="\t\t\treturn winner, true, nil\n",
        replace='\t\t\treturn winner, key != "0198f4c8-8e50-7f66-8f70-bbbbbbbbbbb1/quiesce/0198f4c8-8e50-7f66-8f70-ddddddddddd1", nil\n',
        count=1,
        run="TestExecuteIdenticalRetryReplays",
        expect="KILLED",
        note="Loses the replay signal for exactly the fixture key; other keys still replay.",
    ),
    Mutant(
        name="N-store-torn",
        path=f"{PACKAGE}/store.go",
        find="\treceipt, err := decodeReceipt(raw)\n\tif err != nil {\n\t\treturn Receipt{}, false, err\n\t}\n",
        replace="\treceipt, err := decodeReceipt(raw)\n\tif err != nil && len(raw) != 4 {\n\t\treturn Receipt{}, false, err\n\t}\n\tif err != nil {\n\t\treturn Receipt{}, false, nil\n\t}\n",
        count=1,
        run="TestStoreLookupAbsenceIsNotFailure",
        expect="KILLED",
        note="Launders exactly 4-byte torn receipts as absence; other torn files still fail integrity.",
    ),
    Mutant(
        name="N-complete-unbound",
        path=f"{PACKAGE}/store.go",
        find="\t} else if !found {\n",
        replace='\t} else if !found && string(result) != "{}" {\n',
        count=1,
        run="TestStoreCompleteRequiresReceipt",
        expect="KILLED",
        note="Admits exactly empty-object completions of unbound keys; other completions still refuse.",
    ),
    Mutant(
        name="N-fencing-remote",
        path=f"{PACKAGE}/fencing.go",
        find="\tif parked && reason == fencing.ParkRemoteOwner {\n\t\treturn observeRemoteWinner(current, presented, observation, authErr)\n\t}\n",
        replace="\tif parked && reason == fencing.ParkRemoteOwner {\n\t\treturn fenceLive(current, authErr)\n\t}\n",
        count=1,
        run="TestObserveFencingRemoteWinnerWinningTokenLeavesState",
        expect="KILLED",
        note="Fences exactly remote parks as well (the relative question is skipped); the winning token under a foreign host pins it.",
    ),
    Mutant(
        name="N-engine-checkoperation",
        path=f"{PACKAGE}/execute.go",
        find="\tif err := terminalbackend.CheckOperation(string(operation), admitted); err != nil {\n",
        replace="\tif err := terminalbackend.CheckOperation(string(operation), admitted); err != nil && operation != terminalbackend.OperationWaitSafeBoundary {\n",
        count=1,
        run="TestExecuteEmptyAdmittedRefusesAtLandedGate/wait-safe-boundary",
        expect="KILLED",
        note="Skips the landed conferral for exactly wait; other rows still wire it.",
    ),
    Mutant(
        name="N-engine-transition",
        path=f"{PACKAGE}/execute.go",
        find="\ttarget, effects, err := terminalbackend.CheckTransition(string(operation), string(source), params.Interactive)\n\tif err != nil {\n",
        replace="\ttarget, effects, err := terminalbackend.CheckTransition(string(operation), string(source), params.Interactive)\n\tif err != nil && source != terminalbackend.StateStopped {\n",
        count=1,
        run="TestExecutePreEffectErrorsRestoreSource/illegal_source_refuses",
        expect="KILLED",
        note="Admits exactly stopped-source transitions past the matrix; other illegal sources still refuse.",
    ),
    Mutant(
        name="N-engine-deadline-pre",
        path=f"{PACKAGE}/execute.go",
        find='\tif !engine.Now().Before(deadline) {\n\t\tfailure := refuse(rowTimeoutCode(operation), "operation deadline")\n\t\treturn buildResult(context, source, source, nil, nil, DispositionReplaySame), failure\n\t}\n',
        replace='\tif !engine.Now().Before(deadline) && operation != terminalbackend.OperationWaitSafeBoundary {\n\t\tfailure := refuse(rowTimeoutCode(operation), "operation deadline")\n\t\treturn buildResult(context, source, source, nil, nil, DispositionReplaySame), failure\n\t}\n',
        count=1,
        run="TestExecuteEntryDeadlineCodes/wait-safe-boundary",
        expect="KILLED",
        note="Skips the entry deadline for exactly wait; other rows still cancel.",
    ),
    Mutant(
        name="N-engine-timeout-code",
        path=f"{PACKAGE}/execute.go",
        find="\tcase terminalbackend.OperationWaitSafeBoundary:\n\t\treturn CodeQuiesceTimeout\n",
        replace="\tcase terminalbackend.OperationWaitSafeBoundary:\n\t\treturn CodeStopTimeout\n",
        count=1,
        run="TestExecuteEntryDeadlineCodes/wait-safe-boundary",
        expect="KILLED",
        note="Reports exactly the wait deadline as stop_timeout; the stop row still reports its own.",
    ),
    Mutant(
        name="N-engine-auth-entry",
        path=f"{PACKAGE}/execute.go",
        find='\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), engine.Now()); err != nil {\n\t\tfailure := err.(*Error)\n\t\treturn buildResult(context, source, source, nil, nil, DispositionFor(failure.Code, false)), failure\n',
        replace='\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), engine.Now()); err != nil && operation != terminalbackend.OperationCreate {\n\t\tfailure := err.(*Error)\n\t\treturn buildResult(context, source, source, nil, nil, DispositionFor(failure.Code, false)), failure\n',
        count=1,
        run="TestExecuteCreateEntryAuthorizationRefuses",
        expect="KILLED",
        note="Skips the pre-bind auth gate for exactly the create row; other rows still gate, and the per-effect recheck still refuses — but the receipt is already bound.",
    ),
    Mutant(
        name="N-engine-auth-entry-quiesce",
        path=f"{PACKAGE}/execute.go",
        find='\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), engine.Now()); err != nil {\n\t\tfailure := err.(*Error)\n\t\treturn buildResult(context, source, source, nil, nil, DispositionFor(failure.Code, false)), failure\n',
        replace='\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), engine.Now()); err != nil && context.OperationID != "0198f4c8-8e50-7f66-8f70-ccccccccccc1" {\n\t\tfailure := err.(*Error)\n\t\treturn buildResult(context, source, source, nil, nil, DispositionFor(failure.Code, false)), failure\n',
        count=1,
        run="TestExecutePreEffectErrorsRestoreSource/entry_auth_expired",
        expect="KILLED",
        note="Skips the pre-bind auth gate for exactly the fixture operation; other operations still gate.",
    ),
    Mutant(
        name="N-engine-generation-entry",
        path=f"{PACKAGE}/execute.go",
        find='\tif engine.CurrentGeneration() != context.BackendGeneration {\n\t\tfailure := refuse(CodeStaleGeneration, "backend_generation stale")\n\t\treturn buildResult(context, source, source, nil, nil, DispositionFor(failure.Code, false)), failure\n',
        replace='\tif engine.CurrentGeneration() != context.BackendGeneration && operation != terminalbackend.OperationCreate {\n\t\tfailure := refuse(CodeStaleGeneration, "backend_generation stale")\n\t\treturn buildResult(context, source, source, nil, nil, DispositionFor(failure.Code, false)), failure\n',
        count=1,
        run="TestExecuteCreateEntryGenerationRefuses",
        expect="KILLED",
        note="Skips the pre-bind generation gate for exactly the create row; the loop recheck still refuses but the receipt is already bound.",
    ),
    Mutant(
        name="N-engine-generation-entry-quiesce",
        path=f"{PACKAGE}/execute.go",
        find='\tif engine.CurrentGeneration() != context.BackendGeneration {\n\t\tfailure := refuse(CodeStaleGeneration, "backend_generation stale")\n\t\treturn buildResult(context, source, source, nil, nil, DispositionFor(failure.Code, false)), failure\n',
        replace='\tif engine.CurrentGeneration() != context.BackendGeneration && context.OperationID != "0198f4c8-8e50-7f66-8f70-ccccccccccc1" {\n\t\tfailure := refuse(CodeStaleGeneration, "backend_generation stale")\n\t\treturn buildResult(context, source, source, nil, nil, DispositionFor(failure.Code, false)), failure\n',
        count=1,
        run="TestExecutePreEffectErrorsRestoreSource/entry_generation_stale",
        expect="KILLED",
        note="Skips the pre-bind generation gate for exactly the fixture operation; the loop recheck still refuses but the receipt is already bound.",
    ),
    Mutant(
        name="N-engine-recheck-auth",
        path=f"{PACKAGE}/execute.go",
        find="\t\t\treturn buildResult(context, source, source, performed, evidence, DispositionReplaySame), failure\n\t\t}\n\t\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), engine.Now()); err != nil {\n",
        replace="\t\t\treturn buildResult(context, source, source, performed, evidence, DispositionReplaySame), failure\n\t\t}\n\t\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), engine.Now()); err != nil && committed {\n",
        count=1,
        run="TestExecuteRechecksBeforeEachEffect/rotation_before_first_effect_restores_source",
        expect="KILLED",
        note="Skips the per-effect auth recheck exactly before the first effect; later rechecks stay.",
    ),
    Mutant(
        name="N-engine-recheck-generation",
        path=f"{PACKAGE}/execute.go",
        find="\t\t\treturn buildResult(context, source, after, performed, evidence, DispositionFor(failure.Code, committed)), failure\n\t\t}\n\t\tif engine.CurrentGeneration() != context.BackendGeneration {\n",
        replace="\t\t\treturn buildResult(context, source, after, performed, evidence, DispositionFor(failure.Code, committed)), failure\n\t\t}\n\t\tif engine.CurrentGeneration() != context.BackendGeneration && committed {\n",
        count=1,
        run="TestExecuteRechecksBeforeEachEffect/generation_rotation_before_first_effect_restores_source",
        expect="KILLED",
        note="Skips the per-effect generation recheck exactly before the first effect; later rechecks stay.",
    ),
    Mutant(
        name="N-engine-precommit-after",
        path=f"{PACKAGE}/execute.go",
        find='\t\t\tafter := source\n\t\t\tif committed {\n\t\t\t\tafter = terminalbackend.StateUnavailable\n\t\t\t}\n\t\t\tfailure := refuse(code, "backend effect refused")\n',
        replace='\t\t\tafter := source\n\t\t\tif committed || code == CodeTimeout {\n\t\t\t\tafter = terminalbackend.StateUnavailable\n\t\t\t}\n\t\t\tfailure := refuse(code, "backend effect refused")\n',
        count=1,
        run="TestExecutePreEffectErrorsRestoreSource/coded_backend_refusal_on_first_effect",
        expect="KILLED",
        note="Moves exactly pre-commit timeouts to unavailable; other pre-commit errors still restore source.",
    ),
    Mutant(
        name="N-engine-postcommit-after",
        path=f"{PACKAGE}/execute.go",
        find='\t\t\tafter := source\n\t\t\tif committed {\n\t\t\t\tafter = terminalbackend.StateUnavailable\n\t\t\t}\n\t\t\tfailure := refuse(code, "backend effect refused")\n',
        replace='\t\t\tafter := source\n\t\t\tif committed && code != CodeProcessFailed {\n\t\t\t\tafter = terminalbackend.StateUnavailable\n\t\t\t}\n\t\t\tfailure := refuse(code, "backend effect refused")\n',
        count=1,
        run="TestExecutePostEffectErrorsMoveUnavailable/coded_refusal_on_second_effect",
        expect="KILLED",
        note="Restores source for exactly post-commit process failures; other post-commit errors still fence unavailable.",
    ),
    Mutant(
        name="N-engine-status-match",
        path=f"{PACKAGE}/execute.go",
        find="\tif observed.IdentityMatch != computed {\n",
        replace="\tif observed.IdentityMatch != computed && observed.State != terminalbackend.StateAbsent {\n",
        count=1,
        run="TestExecuteStatusMatchedTupleFalseFormRefuses",
        expect="KILLED",
        note="Admits exactly absent-state match lies; other match lies still refuse.",
    ),
    Mutant(
        name="N-engine-status-unknown",
        path=f"{PACKAGE}/execute.go",
        find='\t\tif code == "" {\n\t\t\treturn empty, refuse(CodeUnavailable, "status observation unknown")\n\t\t}\n',
        replace='\t\tif code == "" {\n\t\t\treturn StatusReport{State: terminalbackend.StateAbsent}, nil\n\t\t}\n',
        count=1,
        run="TestExecuteStatusUnknownIsNeverAbsent",
        expect="KILLED",
        note="Reports exactly uncoded read failures as absent; coded failures still refuse unknown.",
    ),
    Mutant(
        name="N-engine-status-conditional",
        path=f"{PACKAGE}/execute.go",
        find='\tif body.IncludeProviderObservation && !admitted.Has("provider_process_observation") {\n',
        replace='\tif body.IncludeProviderObservation && !admitted.Has("provider_process_observation") && body.TerminalBackendID != "example.backend" {\n',
        count=1,
        run="TestExecuteStatusProviderConditional",
        expect="KILLED",
        note="Admits exactly the fixture backend without the provider capability; others still refuse.",
    ),
    Mutant(
        name="N-status-nullpair",
        path=f"{PACKAGE}/status.go",
        find="\tif hasInstance != hasGeneration {\n",
        replace="\tif hasInstance != hasGeneration && hasInstance {\n",
        count=1,
        run="TestParseStatusBodyNullPairRule",
        expect="KILLED",
        note="Admits exactly instance-null with generation set; the mirrored half still refuses.",
    ),
    Mutant(
        name="N-interim",
        path=f"{PACKAGE}/execute.go",
        find="\tif operation == terminalbackend.OperationCreate {\n\t\treturn terminalbackend.StateCreating\n\t}\n",
        replace="\tif operation == terminalbackend.OperationCreate || operation == terminalbackend.OperationQuiesceInput {\n\t\treturn terminalbackend.StateCreating\n\t}\n",
        count=1,
        run="TestExecuteInterimState",
        expect="KILLED",
        note="Enters creating for exactly quiesce-input as well; other operations still observe source.",
    ),
    Mutant(
        name="N-engine-kind-map",
        path=f"{PACKAGE}/execute.go",
        find="\tcase AuthorizationControl:\n\t\treturn AuthorizationControl, true\n",
        replace="\tcase AuthorizationControl:\n\t\treturn AuthorizationCreate, true\n",
        count=1,
        run="TestExecuteQuiesceSuccess",
        expect="KILLED",
        note="Honors exactly the landed control kind as create; quiesce-input then requests create while the landed table still names control.",
    ),
    Mutant(
        name="N-fencing-operation",
        path=f"{PACKAGE}/fencing.go",
        find="\t_, authErr := fencing.Authorize(fencing.OperationRestore, presented, observation)\n",
        replace="\t_, authErr := fencing.Authorize(fencing.OperationMutation, presented, observation)\n",
        count=1,
        run="TestObserveFencingNonLiveSourcesLeaveState",
        expect="KILLED",
        note="Authorizes through exactly the non-launch mutation entry, which refuses stale tokens instead of parking them; live sources still fence through the verdict fallback, but non-live sources surface the hard refusal instead of the stale_owner park. (Retired in rev4: N-fencing-epoch-only — a stale_owner park implies a decided-stale verdict over the same observation, and both arms call fenceLive with the same refusal, so weakening the park arm is behaviorally equivalent and unkillable; the mismatch fact stays measured by N-fencing-verdict-winner plus the lease-mismatch members of TestRV3F3_GrantLessStaleFences.)",
    ),
    Mutant(
        name="N-engine-timeout-code-stop",
        path=f"{PACKAGE}/execute.go",
        find="\tcase terminalbackend.OperationRequestStop:\n\t\treturn CodeStopTimeout\n",
        replace="\tcase terminalbackend.OperationRequestStop:\n\t\treturn CodeQuiesceTimeout\n",
        count=1,
        run="TestExecuteEntryDeadlineCodes/request-stop",
        expect="KILLED",
        note="Reports exactly the stop deadline as quiesce_timeout; the wait row still reports its own.",
    ),
    Mutant(
        name="N-engine-timeout-code-default",
        path=f"{PACKAGE}/execute.go",
        find="\tcase terminalbackend.OperationRequestStop:\n\t\treturn CodeStopTimeout\n\tdefault:\n\t\treturn CodeTimeout\n\t}\n",
        replace="\tcase terminalbackend.OperationRequestStop:\n\t\treturn CodeStopTimeout\n\tdefault:\n\t\treturn CodeStopTimeout\n\t}\n",
        count=1,
        run="TestExecuteEntryDeadlineCodes/quiesce-input",
        expect="KILLED",
        note="Reports exactly the default-arm rows (create, quiesce) as stop_timeout; wait and stop still report their own.",
    ),
    Mutant(
        name="N-engine-status-source",
        path=f"{PACKAGE}/execute.go",
        find='\tif source != "" {\n',
        replace='\tif source != "" && source != "bogus" {\n',
        count=1,
        run="TestExecuteStatusAllSources",
        expect="KILLED",
        note="Admits exactly the garbage test source past the status matrix; the scripted valid report then succeeds where the killer wants a refusal.",
    ),
    Mutant(
        name="N-params-bootstrap",
        path=f"{PACKAGE}/context.go",
        find="\t\tif _, err := scalar.ParseUUIDv7(params.BootstrapOperationID); err != nil {\n",
        replace='\t\tif _, err := scalar.ParseUUIDv7(params.BootstrapOperationID); err != nil && params.BootstrapOperationID != "nope" {\n',
        count=1,
        run="TestCheckMutationContextParams",
        expect="KILLED",
        note="Admits exactly the nope bootstrap; other malformed bootstraps still refuse.",
    ),
    Mutant(
        name="N-params-quiescence-quiesce",
        path=f"{PACKAGE}/context.go",
        find="\tcase terminalbackend.OperationQuiesceInput:\n\t\tif _, err := scalar.ParseUUIDv7(params.QuiescenceGeneration); err != nil {\n",
        replace='\tcase terminalbackend.OperationQuiesceInput:\n\t\tif _, err := scalar.ParseUUIDv7(params.QuiescenceGeneration); err != nil && params.QuiescenceGeneration != "nope" {\n',
        count=1,
        run="TestCheckMutationContextParams",
        expect="KILLED",
        note="Admits exactly the nope quiescence generation on the quiesce arm; the wait arm still refuses it.",
    ),
    Mutant(
        name="N-params-quiescence-wait",
        path=f"{PACKAGE}/context.go",
        find="\tcase terminalbackend.OperationWaitSafeBoundary:\n\t\tif _, err := scalar.ParseUUIDv7(params.QuiescenceGeneration); err != nil {\n",
        replace='\tcase terminalbackend.OperationWaitSafeBoundary:\n\t\tif _, err := scalar.ParseUUIDv7(params.QuiescenceGeneration); err != nil && params.QuiescenceGeneration != "nope" {\n',
        count=1,
        run="TestCheckMutationContextParams",
        expect="KILLED",
        note="Admits exactly the nope quiescence generation on the wait arm; the quiesce arm still refuses it.",
    ),
    Mutant(
        name="N-params-proof",
        path=f"{PACKAGE}/context.go",
        find="\t\tif _, err := ParseProviderProofKind(string(params.ProviderProofKind)); err != nil {\n",
        replace='\t\tif _, err := ParseProviderProofKind(string(params.ProviderProofKind)); err != nil && string(params.ProviderProofKind) != "provider_restart" {\n',
        count=1,
        run="TestCheckMutationContextParams",
        expect="KILLED",
        note="Admits exactly the provider_restart proof; other malformed proofs still refuse.",
    ),
    Mutant(
        name="N-params-evidence",
        path=f"{PACKAGE}/context.go",
        find="\t\tif _, err := scalar.ParseDigest(params.SafeBoundaryEvidenceID); err != nil {\n",
        replace='\t\tif _, err := scalar.ParseDigest(params.SafeBoundaryEvidenceID); err != nil && params.SafeBoundaryEvidenceID != "not-a-digest" {\n',
        count=1,
        run="TestCheckMutationContextParams",
        expect="KILLED",
        note="Admits exactly the not-a-digest stop evidence; other malformed evidence still refuses.",
    ),
    Mutant(
        name="N-params-graceful",
        path=f"{PACKAGE}/context.go",
        find="\t\tif params.GracefulTimeoutMs < 1 || params.GracefulTimeoutMs > 3600000 {\n",
        replace="\t\tif params.GracefulTimeoutMs < 1 || params.GracefulTimeoutMs > 3600001 {\n",
        count=1,
        run="TestCheckMutationContextParams",
        expect="KILLED",
        note="Admits exactly graceful timeout 3600001; other out-of-bound graceful timeouts still refuse.",
    ),
    Mutant(
        name="N-version-delegation",
        path=f"{PACKAGE}/context.go",
        find="\tif err := terminalbackend.CheckVersionTuple(backendID, implementationVersion, protocolVersion, []string{protocolVersion}); err != nil {\n",
        replace='\tif err := terminalbackend.CheckVersionTuple(backendID, implementationVersion, protocolVersion, []string{protocolVersion}); err != nil && backendID != "example.backend" {\n',
        count=1,
        run="TestParseMutationContextMemberRefusals",
        expect="KILLED",
        note="Skips the landed version-tuple delegation for exactly the fixture backend; other backends still gate.",
    ),
    Mutant(
        name="N-body-scope",
        path=f"{PACKAGE}/bodies.go",
        find="\tif _, ok := operationBodyMembers[parsed]; !ok {\n",
        replace="\tif _, ok := operationBodyMembers[parsed]; !ok && parsed != terminalbackend.OperationCreate {\n",
        count=1,
        run="TestParseOperationBodyScopeGate",
        expect="KILLED",
        note="Admits exactly create past the body scope map; the member-count arm then fires with a different detail, failing the scope killer.",
    ),
    Mutant(
        name="N-body-members",
        path=f"{PACKAGE}/bodies.go",
        find="\tif len(object) != len(want) {\n",
        replace="\tif len(object) != len(want) && len(object) != len(want)+1 {\n",
        count=1,
        run="TestParseOperationBodyRefusals",
        expect="KILLED",
        note="Admits exactly one-extra-member bodies, silently ignoring the smuggled member; other shapes still refuse.",
    ),
    Mutant(
        name="N-store-sweep-age",
        path=f"{PACKAGE}/store.go",
        find="\t\tif now.Sub(info.ModTime()) < stagingSweepAge {\n",
        replace='\t\tif now.Sub(info.ModTime()) < stagingSweepAge && !strings.HasSuffix(entry.Name(), "-live.tmp") {\n',
        count=1,
        run="TestStoreSweepKeepsLiveStaging",
        expect="KILLED",
        note="Sweeps exactly live-suffixed young staging; other young files are still kept.",
    ),
    Mutant(
        name="N-result-effects-sort",
        path=f"{PACKAGE}/result.go",
        find="\tsort.Slice(ordered, func(i, j int) bool { return ordered[i] < ordered[j] })\n",
        replace="\tsort.Slice(ordered, func(i, j int) bool { return ordered[i] > ordered[j] })\n",
        count=1,
        run="TestBuildResultSortsEffectsAndEvidence",
        expect="KILLED",
        note="Reports exactly the inverted effect order; the evidence order still sorts ascending.",
    ),
    Mutant(
        name="N-result-evidence-sort",
        path=f"{PACKAGE}/result.go",
        find="\tsort.Strings(orderedEvidence)\n",
        replace="\tsort.Sort(sort.Reverse(sort.StringSlice(orderedEvidence)))\n",
        count=1,
        run="TestBuildResultSortsEffectsAndEvidence",
        expect="KILLED",
        note="Reports exactly the inverted evidence order; the effect order still sorts ascending.",
    ),
    Mutant(
        name="N-fencing-remote-stale-only",
        path=f"{PACKAGE}/fencing.go",
        find="\tif relativeReason, _, relativeParked := fencing.ParkDetails(relativeErr); relativeParked && relativeReason == fencing.ParkStaleOwner {\n",
        replace="\tif _, _, relativeParked := fencing.ParkDetails(relativeErr); relativeParked {\n",
        count=1,
        run="TestObserveFencingRemoteWinnerFutureEpochLeavesState",
        expect="KILLED",
        note="Fences on any relative park instead of exactly stale_owner; the future-epoch restore_policy member pins it.",
    ),
    Mutant(
        name="N-fencing-remote-lapsed-fallback",
        path=f"{PACKAGE}/fencing.go",
        find="\t// A lapsed grant can defer the relative question before its tuple arm;\n\t// the grant-independent verdict still fences a stale incarnation.\n\tif stale, decided := fencing.StaleRelativeToWinner(presented, observation); decided && stale {\n",
        replace="\t// A lapsed grant can defer the relative question before its tuple arm;\n\t// the grant-independent verdict still fences a stale incarnation.\n\tif stale, decided := fencing.StaleRelativeToWinner(presented, observation); decided && stale && presented.Epoch == observation.Winner.Epoch {\n",
        count=1,
        run="TestObserveFencingRemoteWinnerLapsedGrantFencesStaleIncarnation/stale_epoch",
        expect="KILLED",
        note="Narrows the lapsed-grant fallback to same-epoch losses, leaving the older-epoch stale incarnation active; the direct remote-winner property must still fence both stale shapes.",
    ),
    Mutant(
        name="N-fencing-source-absent",
        path=f"{PACKAGE}/fencing.go",
        find="\t\tterminalbackend.StateActive, terminalbackend.StateQuiescing:\n",
        replace="\t\tterminalbackend.StateActive, terminalbackend.StateQuiescing, terminalbackend.StateAbsent:\n",
        count=1,
        run="TestObserveFencingNonLiveSourcesLeaveState",
        expect="KILLED",
        note="Fences exactly absent as well as the live states; stopped, stale_fenced and unavailable still leave.",
    ),
    Mutant(
        name="N-fencing-source-stopped",
        path=f"{PACKAGE}/fencing.go",
        find="\t\tterminalbackend.StateActive, terminalbackend.StateQuiescing:\n",
        replace="\t\tterminalbackend.StateActive, terminalbackend.StateQuiescing, terminalbackend.StateStopped:\n",
        count=1,
        run="TestObserveFencingNonLiveSourcesLeaveState",
        expect="KILLED",
        note="Fences exactly stopped as well as the live states; absent, stale_fenced and unavailable still leave.",
    ),
    Mutant(
        name="N-fencing-source-creating",
        path=f"{PACKAGE}/fencing.go",
        find="\tcase terminalbackend.StateCreating, terminalbackend.StateParked,\n",
        replace="\tcase terminalbackend.StateParked,\n",
        count=1,
        run="TestObserveFencingNonLiveSourcesLeaveState",
        expect="KILLED",
        note="Fences only parked, active and quiescing; the materializing creating incarnation no longer fences.",
    ),
    Mutant(
        name="N-engine-headless-absent",
        path=f"{PACKAGE}/execute.go",
        find="\tif err := checkCapabilityConditional(operation, params, admitted); err != nil {\n",
        replace="\tif err := checkCapabilityConditional(operation, params, admitted); err != nil && !(operation == terminalbackend.OperationCreate && source == terminalbackend.StateAbsent) {\n",
        count=1,
        run="TestExecuteCreateHeadlessFromAbsentNeedsCapability",
        expect="KILLED",
        note="Skips the headless_creation conditional for exactly a headless create from absent; other conditionals still refuse.",
    ),
    Mutant(
        name="N-engine-committed-timeout-disposition",
        path=f"{PACKAGE}/execute.go",
        find='\t\t\tfailure := refuse(code, "backend effect refused")\n\t\t\treturn buildResult(context, source, after, performed, evidence, DispositionFor(code, committed)), failure\n',
        replace='\t\t\tfailure := refuse(code, "backend effect refused")\n\t\t\treturn buildResult(context, source, after, performed, evidence, DispositionFor(code, committed && code != CodeTimeout)), failure\n',
        count=1,
        run="TestExecuteCreateCommittedTimeoutReportsStatusFirst",
        expect="KILLED",
        note="Reports exactly a committed terminal_backend_timeout as replay_same instead of status_first; other committed codes still route through status.",
    ),
    Mutant(
        name="N-engine-recheck-auth-third",
        path=f"{PACKAGE}/execute.go",
        find="\t\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), engine.Now()); err != nil {\n\t\t\tfailure := err.(*Error)\n\t\t\tafter := source\n",
        replace="\t\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), engine.Now()); err != nil && len(performed) < 2 {\n\t\t\tfailure := err.(*Error)\n\t\t\tafter := source\n",
        count=1,
        run="TestExecuteRechecksBeforeThirdEffect/lease_rotates_before_third_effect",
        expect="KILLED",
        note="Skips the per-effect auth recheck exactly before the third effect; rechecks before effects 1 and 2 stay.",
    ),
    Mutant(
        name="N-engine-recheck-generation-third",
        path=f"{PACKAGE}/execute.go",
        find='\t\tif engine.CurrentGeneration() != context.BackendGeneration {\n\t\t\tfailure := refuse(CodeStaleGeneration, "backend_generation stale")\n\t\t\tafter := source\n',
        replace='\t\tif engine.CurrentGeneration() != context.BackendGeneration && len(performed) < 2 {\n\t\t\tfailure := refuse(CodeStaleGeneration, "backend_generation stale")\n\t\t\tafter := source\n',
        count=1,
        run="TestExecuteRechecksBeforeThirdEffect/generation_rotates_before_third_effect",
        expect="KILLED",
        note="Skips the per-effect generation recheck exactly before the third effect; rechecks before effects 1 and 2 stay.",
    ),
    Mutant(
        name="N-status-session-scoped",
        path=f"{PACKAGE}/execute.go",
        find="\tif observed.SessionID != body.SessionID {\n\t\treturn false, nil\n\t}\n",
        replace="\tif observed.SessionID != body.SessionID && body.HasTerminalInstanceID {\n\t\treturn false, nil\n\t}\n",
        count=1,
        run="TestExecuteStatusSessionDriftRefuses/session_scoped_lying_match_refuses",
        expect="KILLED",
        note="Skips the reported-session comparison for exactly the Session-scoped lookup, adopting a foreign session report; the exact path still compares.",
    ),
    Mutant(
        name="N-status-session-exact",
        path=f"{PACKAGE}/execute.go",
        find="\tif observed.SessionID != body.SessionID {\n\t\treturn false, nil\n\t}\n",
        replace="\tif observed.SessionID != body.SessionID && !body.HasTerminalInstanceID {\n\t\treturn false, nil\n\t}\n",
        count=1,
        run="TestExecuteStatusSessionDriftRefuses/exact_lying_match_refuses",
        expect="KILLED",
        note="Skips the reported-session comparison for exactly the exact-instance lookup, adopting a foreign session report; the Session-scoped path still compares.",
    ),
    Mutant(
        name="N-status-match-instance",
        path=f"{PACKAGE}/execute.go",
        find="\treturn observed.InstanceID == body.TerminalInstanceID &&\n",
        replace="\treturn true &&\n",
        count=1,
        run="TestExecuteStatusIdentityMatchEachAxis/instance/lying_match_refuses",
        expect="KILLED",
        note="Drops exactly the instance conjunct from the identity_match conjunction; the other five axes still compare.",
    ),
    Mutant(
        name="N-status-match-backend",
        path=f"{PACKAGE}/execute.go",
        find="\t\tobserved.BackendID == body.TerminalBackendID &&\n",
        replace="\t\ttrue &&\n",
        count=1,
        run="TestExecuteStatusIdentityMatchEachAxis/backend/lying_match_refuses",
        expect="KILLED",
        note="Drops exactly the backend conjunct from the identity_match conjunction; the other five axes still compare.",
    ),
    Mutant(
        name="N-status-match-implementation",
        path=f"{PACKAGE}/execute.go",
        find="\t\tobserved.ImplVersion == body.ImplementationVersion &&\n",
        replace="\t\ttrue &&\n",
        count=1,
        run="TestExecuteStatusIdentityMatchEachAxis/implementation/lying_match_refuses",
        expect="KILLED",
        note="Drops exactly the implementation conjunct from the identity_match conjunction; the other five axes still compare.",
    ),
    Mutant(
        name="N-status-match-protocol",
        path=f"{PACKAGE}/execute.go",
        find="\t\tobserved.ProtoVersion == body.ProtocolVersion &&\n",
        replace="\t\ttrue &&\n",
        count=1,
        run="TestExecuteStatusIdentityMatchEachAxis/protocol/lying_match_refuses",
        expect="KILLED",
        note="Drops exactly the protocol conjunct from the identity_match conjunction; the other five axes still compare.",
    ),
    Mutant(
        name="N-status-match-generation",
        path=f"{PACKAGE}/execute.go",
        find="\t\tobserved.Generation == body.BackendGeneration, nil\n",
        replace="\t\ttrue, nil\n",
        count=1,
        run="TestExecuteStatusIdentityMatchEachAxis/generation/lying_match_refuses",
        expect="KILLED",
        note="Drops exactly the generation conjunct from the identity_match conjunction; the other five axes still compare.",
    ),
    Mutant(
        name="N-engine-deadline-instant",
        path=f"{PACKAGE}/execute.go",
        find='\tif !engine.Now().Before(deadline) {\n\t\tfailure := refuse(rowTimeoutCode(operation), "operation deadline")\n\t\treturn buildResult(context, source, source, nil, nil, DispositionReplaySame), failure\n\t}\n',
        replace='\tif engine.Now().After(deadline) {\n\t\tfailure := refuse(rowTimeoutCode(operation), "operation deadline")\n\t\treturn buildResult(context, source, source, nil, nil, DispositionReplaySame), failure\n\t}\n',
        count=1,
        run="TestExecuteEntryDeadlineInstantRefuses",
        expect="KILLED",
        note="Admits exactly the now == deadline_at instant at the mutating entry; past-deadline instants still refuse.",
    ),
    Mutant(
        name="N-status-deadline-instant",
        path=f"{PACKAGE}/execute.go",
        find='\tif !engine.Now().Before(deadline) {\n\t\treturn empty, refuse(CodeTimeout, "operation deadline")\n\t}\n',
        replace='\tif engine.Now().After(deadline) {\n\t\treturn empty, refuse(CodeTimeout, "operation deadline")\n\t}\n',
        count=1,
        run="TestExecuteStatusDeadlineInstantRefuses",
        expect="KILLED",
        note="Admits exactly the now == deadline_at instant at the status entry; past-deadline instants still refuse.",
    ),
    Mutant(
        name="N-auth-kind-attach",
        path=f"{PACKAGE}/auth.go",
        find='\tdefault:\n\t\treturn "", refuse(CodeProtocolError, "ax authorization kind")\n\t}\n',
        replace='\tdefault:\n\t\tif value == "attach" {\n\t\t\treturn AuthorizationControl, nil\n\t\t}\n\t\treturn "", refuse(CodeProtocolError, "ax authorization kind")\n\t}\n',
        count=1,
        run="TestParseAuthorizationKindClosed",
        expect="KILLED",
        note="Admits exactly the landed attach name (an AttachAuthorization kind, never an AXAuthorization kind) as control; every other non-kind still refuses.",
    ),
    Mutant(
        name="N-auth-kind-none",
        path=f"{PACKAGE}/auth.go",
        find='\tdefault:\n\t\treturn "", refuse(CodeProtocolError, "ax authorization kind")\n\t}\n',
        replace='\tdefault:\n\t\tif value == "none" {\n\t\t\treturn AuthorizationControl, nil\n\t\t}\n\t\treturn "", refuse(CodeProtocolError, "ax authorization kind")\n\t}\n',
        count=1,
        run="TestParseAuthorizationKindClosed",
        expect="KILLED",
        note="Admits exactly the landed none name (no authorization at all) as control; every other non-kind still refuses.",
    ),
    Mutant(
        name="N-resume-status-error",
        path=f"{PACKAGE}/execute.go",
        find='\treport, err := engine.ExecuteStatus(ctx, body, source, admitted)\n\tif err != nil {\n\t\tfailure := refuse(CodeUnavailable, "idempotency result uncertain")\n\t\treturn buildResult(context, source, terminalbackend.StateUnavailable, nil, nil, DispositionStatusFirst), failure\n\t}\n\tif report.State != source {\n',
        replace='\treport, err := engine.ExecuteStatus(ctx, body, source, admitted)\n\tif err != nil && ErrorCode(err) != CodeTimeout {\n\t\tfailure := refuse(CodeUnavailable, "idempotency result uncertain")\n\t\treturn buildResult(context, source, terminalbackend.StateUnavailable, nil, nil, DispositionStatusFirst), failure\n\t}\n\tif report.State != source && report.State != "" {\n',
        count=1,
        run="TestExecuteUncertainRetryUnknownObservationRefuses/coded_read_failure",
        expect="KILLED",
        note="Admits exactly the timeout-coded failed reconciliation read past the uncertain-refusal arm (one behavioral arm in two adjacent checks: ExecuteStatus returns the empty report on every error path, so the timeout must pass both); every other failed read, and every non-empty non-source report, still refuses.",
    ),
    Mutant(
        name="N-resume-contradiction",
        path=f"{PACKAGE}/execute.go",
        find="\tif report.State != source {\n",
        replace="\tif report.State != source && report.State != terminalbackend.StateParked {\n",
        count=1,
        run="TestExecuteUncertainRetryTargetProvenRefuses/contradictory_observation",
        expect="KILLED",
        note="Resumes on exactly the parked contradiction as well as the source; target-proven, unknown and other contradictions still refuse.",
    ),
    Mutant(
        name="N-resume-target",
        path=f"{PACKAGE}/execute.go",
        find="\tif report.State != source {\n",
        replace="\tif report.State != source && report.State != target {\n",
        count=1,
        run="TestExecuteUncertainRetryTargetProvenRefuses/quiesce_target_proven",
        expect="KILLED",
        note="Resumes on exactly the proven target state as well as the source; contradictory and unknown observations still refuse.",
    ),
    Mutant(
        name="N-resume-scope-instance",
        path=f"{PACKAGE}/execute.go",
        find="\t\tTerminalInstanceID:         context.TerminalInstanceID,\n\t\tHasTerminalInstanceID:      true,\n",
        replace="\t\tTerminalInstanceID:         context.TerminalInstanceID,\n\t\tHasTerminalInstanceID:      false,\n",
        count=1,
        run="TestExecuteUncertainRetryUnknownObservationRefuses/lying_match_on_drifted_instance",
        expect="KILLED",
        note="Reconciles through exactly the Session-scoped lookup instead of the exact instance, adopting a lying instance report; exact reconciliation still refuses it.",
    ),
    Mutant(
        name="N-resume-complete-key",
        path=f"{PACKAGE}/execute.go",
        find="\tif err := engine.Store.Complete(key, encoded); err != nil {\n",
        replace='\tif err := engine.Store.Complete(key+"/resumed", encoded); err != nil {\n',
        count=1,
        run="TestExecuteIdenticalRetryReplays",
        expect="KILLED",
        note="Records the completion under exactly a second key instead of the bound one; the identical retry then reconciles instead of replaying.",
    ),
    Mutant(
        name="N-resume-generation-value",
        path=f"{PACKAGE}/execute.go",
        find='\t\tBackendGeneration:          context.BackendGeneration,\n',
        replace='\t\tBackendGeneration:          "",\n',
        count=1,
        run="TestExecuteUncertainRetryResumesWhenStatusProvesSource",
        expect="KILLED",
        note="Reconciles with exactly an empty generation instead of the request generation; the proof then mismatches and the resumption never proceeds.",
    ),
    Mutant(
        name="N-engine-bind-prelink",
        path=f"{PACKAGE}/execute.go",
        find="\t\t\tif _, found, lookupErr := engine.Store.Lookup(key); lookupErr == nil && !found {\n",
        replace="\t\t\tif _, found, lookupErr := engine.Store.Lookup(key); lookupErr == nil && !found && operation != terminalbackend.OperationQuiesceInput {\n",
        count=1,
        run="TestExecutePreLinkStoreFailureRestoresSource",
        expect="KILLED",
        note="Restores the source on a pre-link store failure for every row except exactly quiesce-input; the quiesce row then fences unavailable.",
    ),
    Mutant(
        name="N-engine-bind-postlink",
        path=f"{PACKAGE}/execute.go",
        find="\t\t\tif _, found, lookupErr := engine.Store.Lookup(key); lookupErr == nil && !found {\n",
        replace="\t\t\tif _, _, lookupErr := engine.Store.Lookup(key); lookupErr == nil {\n",
        count=1,
        run="TestExecuteHookErrorRetryReconcilesThroughStatus/standing_receipt_is_uncertain",
        expect="KILLED",
        note="Restores the source for exactly standing receipts as well as for nothing-durable; the hook-error commit then restores instead of fencing uncertain.",
    ),
    Mutant(
        name="N-fencing-verdict-future",
        path="internal/fencing/staleness.go",
        find="\tif presented.Epoch != observation.Winner.Epoch {\n\t\treturn presented.Epoch < observation.Winner.Epoch, true\n\t}\n",
        replace="\tif presented.Epoch != observation.Winner.Epoch {\n\t\treturn true, true\n\t}\n",
        count=1,
        run="TestRV3F3_GrantLessDecidedNotStaleLeavesState/future_epoch",
        expect="KILLED",
        note="Admits exactly future-epoch grant-less observations as stale; the winning tuple still decides not-stale.",
    ),
    Mutant(
        name="N-fencing-verdict-winner",
        path="internal/fencing/staleness.go",
        find="\treturn presented.LeaseID != observation.Winner.LeaseID, true\n",
        replace='\treturn presented.LeaseID != observation.Winner.LeaseID || presented.LeaseID == "f47ac10b-58cc-4372-a567-0e02b2c3d479", true\n',
        count=1,
        run="TestRV3F3_GrantLessDecidedNotStaleLeavesState/winning_token",
        expect="KILLED",
        note="Admits exactly the winning lease as stale; losing leases still fence and other tuples are unchanged.",
    ),
    Mutant(
        name="N-fencing-verdict-unverified",
        path="internal/fencing/staleness.go",
        find="\tif !observation.Verified {\n\t\treturn false, false\n\t}\n",
        replace="\tif !observation.Verified && presented.Epoch != 1 {\n\t\treturn false, false\n\t}\n",
        count=1,
        run="TestRV3F3_GrantLessUndecidedLeavesState/unverified",
        expect="KILLED",
        note="Decides exactly epoch-1 unverified observations; other unverified members stay undecided.",
    ),
    Mutant(
        name="N-fencing-verdict-ambiguous",
        path="internal/fencing/staleness.go",
        find="\tif observation.Ambiguous {\n\t\treturn false, false\n\t}\n",
        replace="\tif observation.Ambiguous && presented.Epoch != 1 {\n\t\treturn false, false\n\t}\n",
        count=1,
        run="TestRV3F3_GrantLessUndecidedLeavesState/ambiguous",
        expect="KILLED",
        note="Decides exactly epoch-1 ambiguous observations; other ambiguous members stay undecided.",
    ),
    Mutant(
        name="N-fencing-verdict-nowinner",
        path="internal/fencing/staleness.go",
        find="\tif !observation.HasWinner {\n\t\treturn false, false\n\t}\n",
        replace="\tif !observation.HasWinner && presented.Epoch != 1 {\n\t\treturn false, false\n\t}\n",
        count=1,
        run="TestRV3F3_GrantLessUndecidedLeavesState/no_winner",
        expect="KILLED",
        note="Decides exactly epoch-1 winnerless observations; other winnerless members stay undecided.",
    ),
    Mutant(
        name="N-fencing-verdict-winner-shape",
        path="internal/fencing/staleness.go",
        find="\tif observation.Winner.Epoch == 0 || !validLeaseID(observation.Winner.LeaseID) || !validHostID(observation.Winner.HolderHostID) {\n\t\treturn false, false\n\t}\n",
        replace="\tif (observation.Winner.Epoch == 0 || !validLeaseID(observation.Winner.LeaseID) || !validHostID(observation.Winner.HolderHostID)) && presented.Epoch != 1 {\n\t\treturn false, false\n\t}\n",
        count=1,
        run="TestRV3F3_GrantLessUndecidedLeavesState/malformed_winner",
        expect="KILLED",
        note="Decides exactly epoch-1 malformed-winner observations; other malformed winners stay undecided.",
    ),
    Mutant(
        name="N-fencing-verdict-session",
        path="internal/fencing/staleness.go",
        find="\tif presented.SessionID != observation.SessionID {\n\t\treturn false, false\n\t}\n",
        replace="\tif presented.SessionID != observation.SessionID && presented.Epoch != 1 {\n\t\treturn false, false\n\t}\n",
        count=1,
        run="TestRV3F3_GrantLessUndecidedLeavesState/session_mismatch",
        expect="KILLED",
        note="Decides exactly epoch-1 session-mismatched observations; other mismatches stay undecided.",
    ),
    Mutant(
        name="N-fencing-verdict-handoff",
        path="internal/fencing/staleness.go",
        find="\tif observation.HandoffFailed {\n\t\treturn false, false\n\t}\n",
        replace="\tif observation.HandoffFailed && presented.Epoch != 1 {\n\t\treturn false, false\n\t}\n",
        count=1,
        run="TestRV3F3_GrantLessUndecidedLeavesState/failed_handoff",
        expect="KILLED",
        note="Decides exactly epoch-1 failed-handoff observations; the park is otherwise preserved.",
    ),
    Mutant(
        name="N-fencing-verdict-presented-session",
        path="internal/fencing/staleness.go",
        find="\tif _, err := scalar.ParseUUIDv7(presented.SessionID); err != nil {\n\t\treturn false, false\n\t}\n",
        replace="\tif _, err := scalar.ParseUUIDv7(presented.SessionID); err != nil && presented.Epoch != 1 {\n\t\treturn false, false\n\t}\n",
        count=1,
        run="TestRV3F3_GrantLessUndecidedLeavesState/malformed_session",
        expect="KILLED",
        note="Decides exactly the epoch-1 agreed-malformed session (both sides name one malformed session, so only the grammar arm undecides it); other malformed sessions still mismatch first.",
    ),
    Mutant(
        name="N-fencing-verdict-presented-epoch",
        path="internal/fencing/staleness.go",
        find="\tif presented.Epoch == 0 {\n\t\treturn false, false\n\t}\n",
        replace='\tif presented.Epoch == 0 && presented.LeaseID != "6ba7b810-9dad-41d1-80b4-00c04fd430c8" {\n\t\treturn false, false\n\t}\n',
        count=1,
        run="TestRV3F3_GrantLessUndecidedLeavesState/epoch_zero",
        expect="KILLED",
        note="Decides exactly the zero-epoch token under the losing test lease; the zero-epoch winning-lease member stays undecided.",
    ),
    Mutant(
        name="N-fencing-verdict-presented-lease",
        path="internal/fencing/staleness.go",
        find="\tif _, err := scalar.ParseUUIDv4(presented.LeaseID); err != nil {\n\t\treturn false, false\n\t}\n",
        replace="\tif _, err := scalar.ParseUUIDv4(presented.LeaseID); err != nil && presented.Epoch != 1 {\n\t\treturn false, false\n\t}\n",
        count=1,
        run="TestRV3F3_GrantLessUndecidedLeavesState/malformed_lease",
        expect="KILLED",
        note="Decides exactly epoch-1 malformed-lease tokens; other malformed leases stay undecided.",
    ),
    Mutant(
        name="N-fencing-remote-lapsed-not-stale",
        path=f"{PACKAGE}/fencing.go",
        find="\t// A lapsed grant can defer the relative question before its tuple arm;\n\t// the grant-independent verdict still fences a stale incarnation.\n\tif stale, decided := fencing.StaleRelativeToWinner(presented, observation); decided && stale {\n",
        replace="\t// A lapsed grant can defer the relative question before its tuple arm;\n\t// the grant-independent verdict still fences a stale incarnation.\n\tif _, decided := fencing.StaleRelativeToWinner(presented, observation); decided {\n",
        count=1,
        run="TestRV3F3_GrantLessDecidedNotStaleLeavesState",
        expect="KILLED",
        note="Fences a winning or future token from the lapsed remote-winner path by dropping the stale half of the grant-independent fallback; the named no-transition rows fail while the direct remote-offer arm remains present.",
    ),
    Mutant(
        name="N-fencing-remote-lapsed-outer-fallback",
        path=f"{PACKAGE}/fencing.go",
        find="\tif stale, decided := fencing.StaleRelativeToWinner(presented, observation); decided && stale {\n\t\treturn fenceLive(current, authErr)\n\t}\n\treturn current, false, authErr\n}\n\n// observeRemoteWinner resolves a remote-winner park:",
        replace="\tif _, decided := fencing.StaleRelativeToWinner(presented, observation); decided {\n\t\treturn fenceLive(current, authErr)\n\t}\n\treturn current, false, authErr\n}\n\n// observeRemoteWinner resolves a remote-winner park:",
        count=1,
        run="TestRV3F3_GrantLessDecidedNotStaleLeavesState",
        expect="KILLED",
        note="Outer ObserveFencing fallback admits decided-but-not-stale local-winner observations; the winning/future no-transition rows must still reject them. Unique anchor includes the outer return and observeRemoteWinner declaration.",
    ),
    Mutant(
        name="N-engine-recheck-auth-expiry",
        path=f"{PACKAGE}/execute.go",
        find='\tperformed := []terminalbackend.SideEffect(nil)\n\tfor _, effect := range effects {\n\t\tif !engine.Now().Before(deadline) {\n\t\t\tfailure := refuse(rowTimeoutCode(operation), "operation deadline")\n\t\t\tif committed {\n\t\t\t\treturn buildResult(context, source, terminalbackend.StateUnavailable, performed, evidence, DispositionStatusFirst), failure\n\t\t\t}\n\t\t\treturn buildResult(context, source, source, performed, evidence, DispositionReplaySame), failure\n\t\t}\n\t\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), engine.Now()); err != nil {\n',
        replace='\tperformed := []terminalbackend.SideEffect(nil)\n\tentryNow := engine.Now()\n\tfor _, effect := range effects {\n\t\tif !engine.Now().Before(deadline) {\n\t\t\tfailure := refuse(rowTimeoutCode(operation), "operation deadline")\n\t\t\tif committed {\n\t\t\t\treturn buildResult(context, source, terminalbackend.StateUnavailable, performed, evidence, DispositionStatusFirst), failure\n\t\t\t}\n\t\t\treturn buildResult(context, source, source, performed, evidence, DispositionReplaySame), failure\n\t\t}\n\t\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), entryNow); err != nil {\n',
        count=1,
        run="TestRV3W_M1_AuthExpiryRecheckedBeforeEachEffect",
        expect="KILLED",
        note="Drops the per-effect authorization EXPIRY recheck (expiry evaluated at the entry instant) while the lease-tuple recheck stays per-effect; the spanned definition+use is one plant — either half alone breaks the build. Mirrors reviewer narrowing RV3-M1.",
    ),
    Mutant(
        name="N-result-evidence-bound",
        path=f"{PACKAGE}/result.go",
        find="\tif len(evidence) > 256 {\n",
        replace="\tif len(evidence) > 257 {\n",
        count=1,
        run="TestRV3W_M2_EvidenceBoundEdge",
        expect="KILLED",
        note="Admits exactly 257 evidence IDs on the one shared helper both the result and the status surface route through (one site, both surfaces in the killer). Mirrors reviewer narrowing RV3-M2.",
    ),
    Mutant(
        name="N-engine-conditional-disposition",
        path=f"{PACKAGE}/execute.go",
        find="\tif err := checkCapabilityConditional(operation, params, admitted); err != nil {\n\t\tfailure := err.(*Error)\n\t\treturn buildResult(context, source, source, nil, nil, DispositionFor(failure.Code, false)), failure\n",
        replace="\tif err := checkCapabilityConditional(operation, params, admitted); err != nil {\n\t\tfailure := err.(*Error)\n\t\treturn buildResult(context, source, source, nil, nil, DispositionStatusFirst), failure\n",
        count=1,
        run="TestRV3W_M3_ConditionalCapabilityDisposition",
        expect="KILLED",
        note="Reports exactly the capability-conditional arm as status_first instead of the class-mapped required_operator_action. Mirrors reviewer narrowing RV3-M3.",
    ),
    Mutant(
        name="N-proof-sibling",
        path=f"{PACKAGE}/proof.go",
        find='\tdefault:\n\t\treturn "", refuse(CodeProtocolError, "provider proof vocabulary")\n\t}\n',
        replace='\tdefault:\n\t\tif value == "provider_process_observation" {\n\t\t\treturn ProofProviderQuiescence, nil\n\t\t}\n\t\treturn "", refuse(CodeProtocolError, "provider proof vocabulary")\n\t}\n',
        count=1,
        run="TestRV3W_M4_ProofKindSiblingNamesRefused",
        expect="KILLED",
        note="Admits exactly the landed capability name provider_process_observation as a proof kind; every other non-kind still refuses. Mirrors reviewer narrowing RV3-M4.",
    ),
    Mutant(
        name="N-status-last-operation-empty",
        path=f"{PACKAGE}/execute.go",
        find="\tif observed.LastOperationID != nil {\n\t\tif _, err := scalar.ParseUUIDv7(*observed.LastOperationID); err != nil {\n",
        replace='\tif observed.LastOperationID != nil && *observed.LastOperationID != "" {\n\t\tif _, err := scalar.ParseUUIDv7(*observed.LastOperationID); err != nil {\n',
        count=1,
        run="TestRV3W_M8_StatusLastOperationGrammar",
        expect="KILLED",
        note="Admits exactly the empty last_operation_id on status reports; other non-UUIDv7 values still refuse. Mirrors reviewer narrowing RV3-M8.",
    ),
    Mutant(
        name="N-engine-recheck-auth-expiry-third",
        path=f"{PACKAGE}/execute.go",
        find="\tperformed := []terminalbackend.SideEffect(nil)\n\tfor _, effect := range effects {\n",
        replace="\tperformed := []terminalbackend.SideEffect(nil)\n\tentryNow := engine.Now()\n\tfor _, effect := range effects {\n",
        count=1,
        run="TestRV4W_ExpiryRecheckedBeforeThirdEffect",
        expect="KILLED",
        note="Story-close P3-1 (reviewer RV4-M1 mirror): the per-effect authorization EXPIRY is evaluated at the entry instant for the THIRD effect only; positions 1-2 and the tuple recheck stay.",
        find2="\t\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), engine.Now()); err != nil {\n\t\t\tfailure := err.(*Error)\n\t\t\tafter := source\n",
        replace2="\t\tauthNow := engine.Now()\n\t\tif len(performed) >= 2 {\n\t\t\tauthNow = entryNow\n\t\t}\n\t\tif err := CheckAuthorization(context.Authorization, kind, engine.CurrentLease(), authNow); err != nil {\n\t\t\tfailure := err.(*Error)\n\t\t\tafter := source\n",
        count2=1,
    ),
    Mutant(
        name="N-resume-checkresult-stale",
        path=f"{PACKAGE}/execute.go",
        find="\t\tif err := CheckResult(context, source, result); err != nil {\n",
        replace="\t\tif err := CheckResult(context, source, result); err != nil && ErrorCode(err) != CodeStaleGeneration {\n",
        count=1,
        run="TestRV4W_ReplayedImageGenerationBindingAtEngine",
        expect="KILLED",
        note="Story-close P3-2 (reviewer RV4-M6 mirror): the ENGINE replay site returns a stored image whose backend_generation differs from the request as a successful replay; every other CheckResult refusal still refuses.",
    ),
    Mutant(
        name="N-resume-checkresult-disposition",
        path=f"{PACKAGE}/execute.go",
        find="\t\t\treturn buildResult(context, source, terminalbackend.StateUnavailable, nil, nil, DispositionFor(failure.Code, true)), failure\n",
        replace="\t\t\treturn buildResult(context, source, terminalbackend.StateUnavailable, nil, nil, DispositionReplaySame), failure\n",
        count=1,
        run="TestRV4W_ReplayedImageGenerationBindingAtEngine",
        expect="KILLED",
        note="Story-close P3-2 (reviewer RV4-M6b mirror): a refused replayed image reports replay_same instead of the class-mapped status_first. Same killer as the stale row, killed by the disposition assertion.",
    ),
    Mutant(
        name="N-resume-corrupt-image",
        path=f"{PACKAGE}/execute.go",
        find="\t\tvar result Result\n\t\tif err := json.Unmarshal(stored, &result); err != nil {\n",
        replace="\t\tvar result Result\n\t\tif err := json.Unmarshal(stored, &result); err != nil && (len(stored) == 0 || stored[0] != '{') {\n",
        count=1,
        run="TestRV4_CorruptCompletionImageIsIntegrityFailure",
        expect="KILLED",
        note="Story-close P3-2: admits exactly brace-led corrupt completion bytes past the integrity arm; other corrupt shapes still refuse.",
    ),
    Mutant(
        name="N-engine-loop-deadline-instant",
        path=f"{PACKAGE}/execute.go",
        find='\t\tif !engine.Now().Before(deadline) {\n\t\t\tfailure := refuse(rowTimeoutCode(operation), "operation deadline")\n\t\t\tif committed {\n',
        replace='\t\tif engine.Now().After(deadline) {\n\t\t\tfailure := refuse(rowTimeoutCode(operation), "operation deadline")\n\t\t\tif committed {\n',
        count=1,
        run="TestRV4W_LoopDeadlineInstantCancelsWaiting",
        expect="KILLED",
        note="Story-close P3-3 (reviewer RV4-M7 mirror): the in-loop deadline check admits exactly the deadline instant between effects; the entry check is unchanged.",
    ),
    Mutant(
        name="N-auth-kind-case",
        path=f"{PACKAGE}/auth.go",
        find='\tdefault:\n\t\treturn "", refuse(CodeProtocolError, "ax authorization kind")\n\t}\n',
        replace='\tdefault:\n\t\tif value == "Control" {\n\t\t\treturn AuthorizationControl, nil\n\t\t}\n\t\treturn "", refuse(CodeProtocolError, "ax authorization kind")\n\t}\n',
        count=1,
        run="(TestRV4W_AuthorizationKindCaseSiblingRefused|TestParseAuthorizationKindClosed)",
        expect="KILLED",
        note="Story-close P3-4 (reviewer RV4-M5 mirror): the case-variant spelling Control parses as control at the direct and the document entry; every other sibling still refuses.",
    ),
    Mutant(
        name="C-control",
        path=f"{PACKAGE}/doc.go",
        find="// Composition, not re-implementation: the eight-state enum, the ten-operation\n",
        replace="// Composition, not re-implementation (control): the eight-state enum, the ten-operation\n",
        count=1,
        run="TestRequiresProviderObservation",
        expect="SURVIVED",
        note="Harmless control: a comment-only edit must survive.",
    ),
]


def run_mutant(mutant: Mutant) -> str:
    target = REPO / mutant.path
    original = target.read_text()
    found = original.count(mutant.find)
    if found != mutant.count:
        return f"ERROR: {mutant.name}: patch anchors {found}, want {mutant.count}"
    if mutant.find2:
        found2 = original.count(mutant.find2)
        if found2 != mutant.count2:
            return f"ERROR: {mutant.name}: second anchors {found2}, want {mutant.count2}"
    with tempfile.TemporaryDirectory() as staging:
        backup = Path(staging) / "backup"
        shutil.copy2(target, backup)
        try:
            patched = original.replace(mutant.find, mutant.replace)
            if mutant.find2:
                patched = patched.replace(mutant.find2, mutant.replace2)
            target.write_text(patched)
            run = subprocess.run(
                ["go", "test", f"./{PACKAGE}/", "-run", mutant.run, "-count=1"],
                cwd=REPO,
                capture_output=True,
                text=True,
                timeout=300,
            )
        finally:
            shutil.copy2(backup, target)
    output = (run.stdout + run.stderr).strip()
    if os.environ.get("AX_MUTANT_VERBOSE") == "1":
        print(f"--- raw: {mutant.name}: exit {run.returncode} ---", flush=True)
        print(output, flush=True)
        print(f"--- end raw: {mutant.name} ---", flush=True)
    if 'build failed' in output or '\n# ' in output or output.startswith('# '):
        return f"ERROR: {mutant.name}: build broke under the patch"
    if run.returncode == 0:
        verdict = "SURVIVED"
    elif '--- FAIL' in output or 'FAIL:' in output:
        verdict = "KILLED"
    else:
        return f"ERROR: {mutant.name}: exit {run.returncode} with no kill line"
    mark = "ok" if verdict == mutant.expect else "MISMATCH"
    return f"{mark}: {mutant.name}: {verdict} (want {mutant.expect}) :: {mutant.note} [exit {run.returncode}]"


def main(argv: list[str]) -> int:
    selected = [m for m in MUTANTS if not argv or m.name in argv]
    if argv and len(selected) != len(argv):
        unknown = sorted(set(argv) - {m.name for m in selected})
        print(f"unknown mutants: {', '.join(unknown)}")
        return 2
    failures = 0
    for mutant in selected:
        try:
            line = run_mutant(mutant)
        except subprocess.TimeoutExpired:
            line = f"ERROR: {mutant.name}: killer timed out"
        print(line, flush=True)
        if not line.startswith("ok:"):
            failures += 1
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
