import json, subprocess, hashlib
SRC='internal/terminalbackend/manifest.go'
ORIG=open(SRC).read()
MUTANTS=[
 ("M12-identity-recompute","delete",
  '\tcomputed, err := objectIdentity(object, selfField)\n\tif err != nil {\n\t\treturn err\n\t}\n\tif computed != claimed {\n\t\treturn mismatchf("document identity binding")\n\t}\n',
  '\tif _, err := objectIdentity(object, selfField); err != nil {\n\t\treturn err\n\t}\n'),
 ("M23-liveness-future","narrow",
  '\tif observed.After(now) || !now.Before(expires) {',
  '\tif _ = observed; !now.Before(expires) {'),
 ("M25-liveness-delete","delete",
  '\tif observed.After(now) || !now.Before(expires) {\n\t\treturn mismatchf("evidence liveness")\n\t}\n',
  '\t_, _ = observed, expires\n'),
 ("M30-signature-ignore","delete",
  '\tif err := verify(object.IssuerID, message, object.AttestationSignature); err != nil {\n\t\treturn integrityFailure("evidence attestation")\n\t}\n',
  '\t_ = verify(object.IssuerID, message, object.AttestationSignature)\n'),
 ("M31-generation-binding-delete","delete",
  '\tif digest != probe.BackendGenerationDigest {\n\t\treturn &Error{Code: CodeStaleGeneration, BackendID: probe.TerminalBackendID, Detail: "probe generation binding"}\n\t}\n',
  '\t_ = digest\n'),
 ("M34-evidence-false-claim","narrow",
  '\t\tif !present || !claim.Value {\n\t\t\treturn nil, mismatchf("evidence claim binding")\n\t\t}\n',
  '\t\t_ = claim\n\t\tif !present {\n\t\t\treturn nil, mismatchf("evidence claim binding")\n\t\t}\n'),
 ("M35-probe-protocol-membership","delete",
  '\tif !member {\n\t\treturn mismatchf("probe protocol membership")\n\t}\n',
  '\t_ = member\n'),
 ("M43-conflicting-evidence","narrow",
  '\t\tif previous, duplicate := seen[object.EvidenceID]; duplicate {\n\t\t\tif !equalEvidence(previous, object) {\n\t\t\t\treturn nil, mismatchf("conflicting evidence")\n\t\t\t}\n\t\t\tcontinue\n\t\t}\n',
  '\t\tif _, duplicate := seen[object.EvidenceID]; duplicate {\n\t\t\tcontinue\n\t\t}\n'),
 ("M47-evidence-expiry-order","narrow",
  '\tif !expires.After(observed) {\n\t\treturn Evidence{}, mismatchf("evidence expiry")\n\t}\n',
  '\t_, _ = observed, expires\n'),
 ("M51-coverage-delete","delete",
  '\t\tif !covered {\n\t\t\treturn mismatchf("evidence requirement coverage")\n\t\t}\n',
  '\t\t_ = covered\n'),
 ("M54-claim-registry-binding","delete",
  '\tif generationVariable != row.generationVariable ||\n\t\t!equalStrings(operations, row.dependentOperations) ||\n\t\t!equalStrings(requirements, row.evidenceRequirements) {\n\t\treturn Claim{}, mismatchf("capability registry binding")\n\t}\n',
  '\t_ = row\n'),
 ("M59-extensions-nonempty","narrow",
  '\textensions, ok := raw.(map[string]any)\n\tif !ok || len(extensions) != 0 {',
  '\t_, ok := raw.(map[string]any)\n\tif !ok {'),
 # extra narrowing mutants on canonicalization / digest domains
 ("M61-signed-drop-observed","narrow",
  '\t\t"observed_at":                evidence.ObservedAt.String(),\n', ''),
 ("M62-signed-drop-backend-id","narrow",
  '\t\t"terminal_backend_id":        evidence.TerminalBackendID,\n', ''),
 ("M63-signed-drop-os-version","narrow",
  '\t\t"os_version":                 evidence.OSVersion,\n', ''),
 ("M64-signed-drop-fixture","narrow",
  '\t\t"conformance_fixture_id":     evidence.ConformanceFixtureID,\n', ''),
 ("M65-signed-drop-issuer","narrow",
  '\t\t"issuer":                     evidence.Issuer,\n', ''),
 ("M66-signed-drop-protocol","narrow",
  '\t\t"protocol_version":           evidence.ProtocolVersion,\n', ''),
 ("M67-signed-drop-sentinel","narrow",
  '\t\t"sentinel_result":            nullableString(evidence.SentinelResult),\n', ''),
 ("M68-signed-drop-provider-id","narrow",
  '\t\t"provider_id":                nullableString(evidence.ProviderID),\n', ''),
 ("M69-signed-drop-provider-build","narrow",
  '\t\t"provider_build":             nullableString(evidence.ProviderBuild),\n', ''),
 ("M70-signed-drop-smoke","narrow",
  '\t\t"provider_auth_smoke_result": nullableString(evidence.ProviderAuthSmokeResult),\n', ''),
 ("M71-signed-no-jcs","narrow",
  '\tcanonical, err := jcs.Transform(serialized)\n\tif err != nil {\n\t\treturn nil, integrityFailure("evidence canonical bytes")\n\t}\n',
  '\tcanonical := serialized\n'),
 ("M72-identity-no-jcs","narrow",
  '\tcanonical, err := jcs.Transform(serialized)\n\tif err != nil {\n\t\treturn "", mismatchf("document identity")\n\t}\n',
  '\tcanonical := serialized\n'),
 ("M73-identity-omit-nothing","narrow",
  '\t\tif name != selfField {\n\t\t\tomitted[name] = member\n\t\t}\n',
  '\t\tomitted[name] = member\n'),
 ("M74-generation-domain-truncate","narrow",
  '\tmaterial := append([]byte(generationDigestDomain), rawGeneration...)',
  '\tmaterial := append([]byte("ax-terminal-backend-generation-v1"), rawGeneration...)'),
 ("M75-signed-domain-no-nul","narrow",
  '\tmessage := append([]byte(evidenceSignatureDomain), 0x00)',
  '\tmessage := []byte(evidenceSignatureDomain)'),
 ("M76-evidence-ids-unsorted","narrow",
  '\tfor index := range want {\n\t\tfor next := index + 1; next < len(want); next++ {\n\t\t\tif want[next] < want[index] {\n\t\t\t\twant[index], want[next] = want[next], want[index]\n\t\t\t}\n\t\t}\n\t}\n',
  ''),
 ("M77-admitted-requires-nothing","narrow",
  '\tfor capability, claim := range probeClaims {\n\t\tif claim.Value {\n\t\t\tcapabilities = append(capabilities, capability)\n\t\t}\n\t}\n',
  '\tfor capability := range probeClaims {\n\t\tcapabilities = append(capabilities, capability)\n\t}\n'),
 ("M78-hasoperation-any","narrow",
  '\t\tfor _, conferred := range row.dependentOperations {\n\t\t\tif conferred == operation {\n\t\t\t\treturn true\n\t\t\t}\n\t\t}\n',
  '\t\tif len(row.dependentOperations) > 0 {\n\t\t\treturn true\n\t\t}\n'),
 ("M79-decode-depth","narrow",
  '\tif depth > maxJSONDepth {\n\t\treturn nil, mismatchf("document nesting")\n\t}\n', ''),
 ("M80-decode-trailing","delete",
  '\tif decoder.More() {\n\t\treturn nil, mismatchf("document trailing data")\n\t}\n', ''),
 ("M81-decode-utf8","delete",
  '\tif !utf8.Valid(raw) {\n\t\treturn nil, mismatchf("document encoding")\n\t}\n', ''),
 ("M82-array-nil-init","narrow",
  '\t\t\tarray := []any{}', '\t\t\tvar array []any'),
 ("M83-probe-availability","delete",
  '\tswitch availability {\n\tcase AvailabilityAvailable, AvailabilityConditional, AvailabilityUnavailable, AvailabilityUnknown:\n\tdefault:\n\t\treturn Probe{}, mismatchf("probe availability")\n\t}\n', ''),
 ("M84-evidence-issuer-vocab","delete",
  '\tif issuer != IssuerRelease && issuer != IssuerLocalProbe {\n\t\treturn Evidence{}, mismatchf("evidence issuer")\n\t}\n', ''),
 ("M85-manifest-digest-kind","delete",
  '\tif needsDigest(kind) == (digest == "") {\n\t\treturn Manifest{}, mismatchf("manifest executable digest")\n\t}\n', ''),
 ("M86-manifest-backend-id","delete",
  '\tif _, err := ParseID(backendID); err != nil {\n\t\treturn Manifest{}, mismatchf("manifest backend identity")\n\t}\n', ''),
 ("M87-manifest-schema","delete",
  '\tif schema, err := stringMember(object, "schema"); err != nil || schema != SchemaManifest {\n\t\treturn Manifest{}, mismatchf("manifest schema")\n\t}\n', ''),
 ("M88-protocol-major","narrow",
  '\t\tif !semverPattern.MatchString(version) || semverMajor(version) != 1 {',
  '\t\tif !semverPattern.MatchString(version) {'),
 ("M89-platform-bound","narrow",
  '\tif len(names) == 0 || len(names) > 4 {', '\tif len(names) > 4 {'),
 ("M90-claims-bound","narrow",
  '\tif len(array) > maxClaims {\n\t\treturn nil, mismatchf("claim list bound")\n\t}\n', ''),
 ("M91-evidence-ids-bound","narrow",
  '\tif len(evidenceIDs) > maxEvidenceIDs {\n\t\treturn Probe{}, mismatchf("evidence list bound")\n\t}\n', ''),
 ("M92-registry-nil","delete",
  '\tif registry == nil {\n\t\treturn Admitted{}, &Error{Code: CodeNotFound, Detail: "registry unavailable"}\n\t}\n', ''),
 ("M93-realm-plainclaim-null","narrow",
  '\t} else if bindingID != "" || providerID != "" || providerBuild != "" ||\n\t\tsentinelResult != "" || smokeResult != "" {\n\t\treturn realmMembers{}, mismatchf("evidence realm binding")\n\t}\n',
  '\t}\n'),
 ("M94-realm-literal-passed","narrow",
  '\tif !ok || value != "passed" {', '\tif !ok {'),
 ("M95-digest-or-null-absence","narrow",
  '\traw, known := object[name]\n\tif !known {\n\t\treturn "", mismatchf("document members")\n\t}\n\tif raw == nil {\n\t\treturn "", nil\n\t}\n\tvalue, ok := raw.(string)\n\tif !ok {\n\t\treturn "", mismatchf("document member type")\n\t}\n\tif _, err := scalar.ParseDigest(value); err != nil {\n\t\treturn "", mismatchf("document digest")\n\t}\n\treturn value, nil\n',
  '\traw := object[name]\n\tif raw == nil {\n\t\treturn "", nil\n\t}\n\tvalue, ok := raw.(string)\n\tif !ok {\n\t\treturn "", mismatchf("document member type")\n\t}\n\tif _, err := scalar.ParseDigest(value); err != nil {\n\t\treturn "", mismatchf("document digest")\n\t}\n\treturn value, nil\n'),
]
results=[]
for mid,kind,old,new in MUTANTS:
    if ORIG.count(old)!=1:
        results.append((mid,kind,"ANCHOR-BAD",ORIG.count(old))); continue
    open(SRC,'w').write(ORIG.replace(old,new,1))
    b=subprocess.run(['go','vet','./internal/terminalbackend/'],capture_output=True,text=True)
    if b.returncode!=0:
        results.append((mid,kind,"COMPILE-FAIL",b.stderr.strip().splitlines()[1:3]))
        open(SRC,'w').write(ORIG); continue
    r=subprocess.run(['go','test','./internal/terminalbackend/','-count=1'],capture_output=True,text=True)
    results.append((mid,kind,"KILLED" if r.returncode!=0 else "SURVIVED",""))
    open(SRC,'w').write(ORIG)
assert hashlib.sha256(open(SRC,'rb').read()).hexdigest()=="d5a7b8cccf9670f98eb6e85cdbe76226fc8a293685177f685e0111fa74c7ab85","REVERT FAILED"
json.dump(results,open('.temp/TASK-260830-1zvmw7/mutants2.json','w'),indent=1)
for r in results: print(f"{r[0]:42s} {r[1]:8s} {r[2]}  {r[3] if r[3] else ''}")
k=sum(1 for r in results if r[2]=="KILLED"); s=sum(1 for r in results if r[2]=="SURVIVED")
print(f"\nKILLED {k} / SURVIVED {s} / OTHER {len(results)-k-s}")
