import json, os, shutil, subprocess, sys, hashlib

SRC = 'internal/terminalbackend/manifest.go'
ORIG = open(SRC).read()

MUTANTS = [
 # id, kind, old, new
 ("M01-probe-schema","delete",
  '\tif schema, err := stringMember(object, "schema"); err != nil || schema != SchemaProbe {\n\t\treturn Probe{}, mismatchf("probe schema")\n\t}\n',
  ''),
 ("M02-probe-schema-version","delete",
  '\tif version, err := stringMember(object, "schema_version"); err != nil || version != SchemaVersion100 {\n\t\treturn Probe{}, mismatchf("probe schema version")\n\t}\n',
  ''),
 ("M03-probe-backend-id","delete",
  '\tif _, err := ParseID(backendID); err != nil {\n\t\treturn Probe{}, mismatchf("probe backend identity")\n\t}\n',
  ''),
 ("M04-probe-kind","narrow",
  '\tkind, err := parseKind(kindName)\n\tif err != nil {\n\t\treturn Probe{}, mismatchf("probe implementation kind")\n\t}\n',
  '\tkind, _ := parseKind(kindName)\n'),
 ("M05-probe-digest-kind","delete",
  '\tif needsDigest(kind) == (digest == "") {\n\t\treturn Probe{}, mismatchf("probe executable digest")\n\t}\n',
  ''),
 ("M06-evidence-schema","delete",
  '\tif schema, err := stringMember(object, "schema"); err != nil || schema != SchemaCapabilityEvidence {\n\t\treturn Evidence{}, mismatchf("evidence schema")\n\t}\n',
  ''),
 ("M07-evidence-schema-version","delete",
  '\tif version, err := stringMember(object, "schema_version"); err != nil || version != SchemaVersion100 {\n\t\treturn Evidence{}, mismatchf("evidence schema version")\n\t}\n',
  ''),
 ("M08-evidence-backend-id","delete",
  '\tif _, err := ParseID(backendID); err != nil {\n\t\treturn Evidence{}, mismatchf("evidence backend identity")\n\t}\n',
  ''),
 ("M09-evidence-protocol-major","delete",
  '\tif semverMajor(protocolVersion) != 1 {\n\t\treturn Evidence{}, mismatchf("evidence protocol major 1")\n\t}\n',
  ''),
 ("M10-manifest-kind","narrow",
  '\tkind, err := parseKind(kindName)\n\tif err != nil {\n\t\treturn Manifest{}, mismatchf("manifest implementation kind")\n\t}\n',
  '\tkind, _ := parseKind(kindName)\n'),
 ("M11-exact-members-extra","narrow",
  '\tif len(object) != len(members) {\n\t\treturn mismatchf("document members")\n\t}\n',
  '\tif len(object) < len(members) {\n\t\treturn mismatchf("document members")\n\t}\n'),
 ("M12-identity-recompute","delete",
  '\tif computed != claimed {\n\t\treturn mismatchf("document identity binding")\n\t}\n',
  ''),
 ("M13-generation-domain","narrow",
  '\tmaterial := append([]byte(generationDigestDomain), rawGeneration...)',
  '\tmaterial := []byte(rawGeneration)'),
 ("M14-generation-empty","narrow",
  '\tif !utf8.ValidString(rawGeneration) || len(rawGeneration) < 1 || len(rawGeneration) > maxGenerationBytes {',
  '\tif !utf8.ValidString(rawGeneration) || len(rawGeneration) > maxGenerationBytes {'),
 ("M15-signed-domain","narrow",
  '\tmessage := append([]byte(evidenceSignatureDomain), 0x00)',
  '\tmessage := []byte{}'),
 ("M16-signed-drop-capability","narrow",
  '\t\t"capability":                 evidence.Capability,\n',
  ''),
 ("M17-signed-drop-generation","narrow",
  '\t\t"backend_generation_digest":  evidence.BackendGenerationDigest,\n',
  ''),
 ("M18-signed-drop-expires","narrow",
  '\t\t"expires_at":                 evidence.ExpiresAt.String(),\n',
  ''),
 ("M19-signed-drop-facts","narrow",
  '\t\t"facts":                      stringsToValues(evidence.Facts),\n',
  ''),
 ("M20-signed-drop-issuer-id","narrow",
  '\t\t"issuer_id":                  evidence.IssuerID,\n',
  ''),
 ("M21-signed-drop-realm-binding","narrow",
  '\t\t"terminal_binding_id":        nullableDigest(evidence.TerminalBindingID),\n',
  ''),
 ("M22-signed-drop-platform","narrow",
  '\t\t"platform":                   evidence.Platform.String(),\n',
  ''),
 ("M23-liveness-future","narrow",
  '\tif observed.After(now) || !now.Before(expires) {',
  '\tif !now.Before(expires) {'),
 ("M24-liveness-boundary","narrow",
  '\tif observed.After(now) || !now.Before(expires) {',
  '\tif observed.After(now) || now.After(expires) {'),
 ("M25-liveness-delete","delete",
  '\tif observed.After(now) || !now.Before(expires) {\n\t\treturn mismatchf("evidence liveness")\n\t}\n',
  ''),
 ("M26-factscover-delete","delete",
  '\tfor _, requirement := range requirements {\n\t\tif !held[requirementFact[requirement]] {\n\t\t\treturn false\n\t\t}\n\t}\n',
  ''),
 ("M27-factscover-first-only","narrow",
  '\tfor _, requirement := range requirements {\n\t\tif !held[requirementFact[requirement]] {\n\t\t\treturn false\n\t\t}\n\t}\n',
  '\tif len(requirements) > 0 && !held[requirementFact[requirements[0]]] {\n\t\treturn false\n\t}\n'),
 ("M28-evidence-ids-delete","delete",
  '\tif !equalStrings(probe.EvidenceIDs, want) {\n\t\treturn mismatchf("evidence id set binding")\n\t}\n',
  ''),
 ("M29-evidence-ids-subset","narrow",
  '\tif !equalStrings(probe.EvidenceIDs, want) {\n\t\treturn mismatchf("evidence id set binding")\n\t}\n',
  '\tif len(probe.EvidenceIDs) < len(want) {\n\t\treturn mismatchf("evidence id set binding")\n\t}\n'),
 ("M30-signature-ignore","delete",
  '\tif err := verify(object.IssuerID, message, object.AttestationSignature); err != nil {\n\t\treturn integrityFailure("evidence attestation")\n\t}\n',
  ''),
 ("M31-generation-binding-delete","delete",
  '\tif digest != probe.BackendGenerationDigest {\n\t\treturn &Error{Code: CodeStaleGeneration, BackendID: probe.TerminalBackendID, Detail: "probe generation binding"}\n\t}\n',
  ''),
 ("M32-override-stable-delete","narrow",
  '\t\tcase exists && !static.GenerationVariable:\n\t\t\treturn mismatchf("probe override of stable claim")\n',
  ''),
 ("M33-omission-delete","delete",
  '\tfor capability := range manifest {\n\t\tif _, present := indexProbeCapability(probe, capability); !present {\n\t\t\treturn mismatchf("probe omission of manifest claim")\n\t\t}\n\t}\n',
  ''),
 ("M34-evidence-false-claim","narrow",
  '\t\tif !present || !claim.Value {\n\t\t\treturn nil, mismatchf("evidence claim binding")\n\t\t}\n',
  '\t\tif !present {\n\t\t\treturn nil, mismatchf("evidence claim binding")\n\t\t}\n'),
 ("M35-probe-protocol-membership","delete",
  '\tif !member {\n\t\treturn mismatchf("probe protocol membership")\n\t}\n',
  ''),
 ("M36-record-binding-delete","delete",
  '\tif manifest.ImplementationVersion != record.ImplementationVersion ||\n\t\tmanifest.ImplementationKind != record.Kind ||\n\t\t!equalStrings(manifest.ProtocolVersions, record.ProtocolVersions) ||\n\t\t!equalPlatforms(manifest.Platforms, record.Platforms) {\n\t\treturn &Error{Code: CodeDrift, BackendID: manifest.TerminalBackendID, Detail: "manifest implementation drift"}\n\t}\n',
  ''),
 ("M37-check-operation-vocab","delete",
  '\tif !operationVocabulary[operation] {\n\t\treturn mismatchf("operation vocabulary")\n\t}\n\tif !admitted.HasOperation(operation) {',
  '\tif !admitted.HasOperation(operation) {'),
 ("M38-realm-required-delete","narrow",
  '\tif isRealm {\n\t\tif bindingID == "" || providerID == "" || providerBuild == "" ||\n\t\t\tsentinelResult == "" || smokeResult == "" {\n\t\t\treturn realmMembers{}, mismatchf("evidence realm binding")\n\t\t}\n\t} else if',
  '\tif isRealm {\n\t} else if'),
 ("M39-signature-scheme","narrow",
  '\traw, found := strings.CutPrefix(encoded, signatureSchemePrefix)\n\tif !found || raw == "" {',
  '\traw, _ := strings.CutPrefix(encoded, signatureSchemePrefix)\n\tif raw == "" {'),
 ("M40-closedlist-nonempty","narrow",
  '\tif len(values) > max || (requireNonEmpty && len(values) == 0) {',
  '\tif len(values) > max {'),
 ("M41-sortedunique-dup","narrow",
  '\t\tif index > 0 && values[index-1] >= values[index] {\n\t\t\treturn mismatchf("document ordering")\n\t\t}\n',
  '\t\tif index > 0 && values[index-1] > values[index] {\n\t\t\treturn mismatchf("document ordering")\n\t\t}\n'),
 ("M42-duplicate-key","delete",
  '\t\t\t\tif _, duplicate := object[key]; duplicate {\n\t\t\t\t\treturn nil, mismatchf("document duplicate member")\n\t\t\t\t}\n',
  ''),
 ("M43-conflicting-evidence","narrow",
  '\t\t\tif !equalEvidence(previous, object) {\n\t\t\t\treturn nil, mismatchf("conflicting evidence")\n\t\t\t}\n',
  ''),
 ("M44-manifest-probed-origin","narrow",
  '\tif origin != OriginStatic && (origin != OriginProbed || !allowProbed) {',
  '\tif origin != OriginStatic && origin != OriginProbed {'),
 ("M45-bounded-upper","narrow",
  '\tif !utf8.ValidString(value) || len(value) < 1 || len(value) > maxOpaqueString {\n\t\treturn "", mismatchf("document string bound")\n\t}\n',
  '\tif !utf8.ValidString(value) || len(value) < 1 {\n\t\treturn "", mismatchf("document string bound")\n\t}\n'),
 ("M46-evidence-value-true","narrow",
  '\tif value, ok := object["value"].(bool); !ok || !value {\n\t\treturn Evidence{}, mismatchf("evidence value")\n\t}\n',
  '\tif _, ok := object["value"].(bool); !ok {\n\t\treturn Evidence{}, mismatchf("evidence value")\n\t}\n'),
 ("M47-evidence-expiry-order","narrow",
  '\tif !expires.After(observed) {\n\t\treturn Evidence{}, mismatchf("evidence expiry")\n\t}\n',
  ''),
 ("M48-tuple-binding-delete","delete",
  '\tif object.TerminalBackendID != probe.TerminalBackendID ||\n\t\tobject.ImplementationVersion != probe.ImplementationVersion ||\n\t\tobject.ProtocolVersion != probe.ProtocolVersion ||\n\t\tobject.BackendGenerationDigest != probe.BackendGenerationDigest ||\n\t\tobject.Platform != probe.Platform ||\n\t\tobject.OSVersion != probe.OSVersion ||\n\t\tobject.ConformanceFixtureID != manifest.ConformanceFixtureID {\n\t\treturn mismatchf("evidence tuple binding")\n\t}\n',
  ''),
 ("M49-tuple-binding-narrow-generation","narrow",
  '\t\tobject.BackendGenerationDigest != probe.BackendGenerationDigest ||\n',
  ''),
 ("M50-tuple-binding-narrow-fixture","narrow",
  '\t\tobject.ConformanceFixtureID != manifest.ConformanceFixtureID {',
  '\t\tfalse {'),
 ("M51-coverage-delete","delete",
  '\t\tif !covered {\n\t\t\treturn mismatchf("evidence requirement coverage")\n\t\t}\n',
  ''),
 ("M52-probe-platform-membership","delete",
  '\tfor _, platform := range manifest.Platforms {\n\t\tif probe.Platform == platform {\n\t\t\treturn nil\n\t\t}\n\t}\n\treturn mismatchf("probe platform membership")\n',
  '\treturn nil\n'),
 ("M53-static-echo-delete","narrow",
  '\t\tcase proved.Origin == OriginStatic:\n\t\t\tif !equalClaim(proved, static) {\n\t\t\t\treturn mismatchf("probe static claim echo")\n\t\t\t}\n',
  '\t\tcase proved.Origin == OriginStatic:\n'),
 ("M54-claim-registry-binding","delete",
  '\tif generationVariable != row.generationVariable ||\n\t\t!equalStrings(operations, row.dependentOperations) ||\n\t\t!equalStrings(requirements, row.evidenceRequirements) {\n\t\treturn Claim{}, mismatchf("capability registry binding")\n\t}\n',
  ''),
 ("M55-nil-verifier","delete",
  '\tif verify == nil {\n\t\treturn Admitted{}, integrityFailure("evidence signature verifier")\n\t}\n',
  ''),
 ("M56-manifest-record-digest","delete",
  '\tif manifest.ExecutableDigest != record.ExecutableDigest {\n\t\treturn &Error{Code: CodeUntrusted, BackendID: manifest.TerminalBackendID, Detail: "executable substitution"}\n\t}\n',
  ''),
 ("M57-probe-identity-delete","delete",
  '\tif probe.TerminalBackendID != manifest.TerminalBackendID ||\n\t\tprobe.ImplementationVersion != manifest.ImplementationVersion ||\n\t\tprobe.ImplementationKind != manifest.ImplementationKind {\n\t\treturn mismatchf("probe manifest binding")\n\t}\n',
  ''),
 ("M58-probe-executable-digest-equality","delete",
  '\tif probe.ExecutableDigest != manifest.ExecutableDigest {\n\t\tif probe.TerminalBackendID == manifest.TerminalBackendID {\n\t\t\treturn &Error{Code: CodeUntrusted, BackendID: probe.TerminalBackendID, Detail: "executable substitution"}\n\t\t}\n\t\treturn mismatchf("probe manifest binding")\n\t}\n',
  ''),
 ("M59-extensions-nonempty","narrow",
  '\tif !ok || len(extensions) != 0 {',
  '\tif !ok {'),
 ("M60-claim-ordering","narrow",
  '\t\tif previous >= claim.Capability {\n\t\t\treturn nil, mismatchf("claim ordering")\n\t\t}\n',
  '\t\tif previous > claim.Capability {\n\t\t\treturn nil, mismatchf("claim ordering")\n\t\t}\n'),
]

results=[]
for mid, kind, old, new in MUTANTS:
    if ORIG.count(old) != 1:
        results.append((mid,kind,"ANCHOR-BAD",ORIG.count(old)))
        continue
    open(SRC,'w').write(ORIG.replace(old,new,1))
    build = subprocess.run(['go','vet','./internal/terminalbackend/'],capture_output=True,text=True)
    if build.returncode!=0:
        results.append((mid,kind,"COMPILE-FAIL",build.stderr.strip().splitlines()[:2]))
        open(SRC,'w').write(ORIG); continue
    run = subprocess.run(['go','test','./internal/terminalbackend/','-count=1'],capture_output=True,text=True)
    status = "KILLED" if run.returncode!=0 else "SURVIVED"
    results.append((mid,kind,status,""))
    open(SRC,'w').write(ORIG)

assert hashlib.sha256(open(SRC,'rb').read()).hexdigest()=="d5a7b8cccf9670f98eb6e85cdbe76226fc8a293685177f685e0111fa74c7ab85", "REVERT FAILED"
json.dump(results, open('.temp/TASK-260830-1zvmw7/mutants.json','w'), indent=1)
for r in results: print(f"{r[0]:42s} {r[1]:8s} {r[2]}  {r[3] if r[3] else ''}")
k=sum(1 for r in results if r[2]=="KILLED"); s=sum(1 for r in results if r[2]=="SURVIVED")
print(f"\nKILLED {k} / SURVIVED {s} / OTHER {len(results)-k-s}")
