package axerror

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/relux-works/agent-session-manager/internal/canonicaljson"
)

// Details is the Section 15.1 diagnostic data map. The pinned document calls it
// "an explicitly open diagnostic data map, not an implicit schema extension":
// unknown keys are admitted as inert data, and nothing in this package derives
// success, authority, or a remediation action from them.
type Details map[string]any

var (
	// ErrInvalidDetails reports a diagnostic map outside the Section 15.1
	// shape, bounds, or redaction rules.
	ErrInvalidDetails = errors.New("invalid structured error details")

	// ErrCausalLeak reports human text or a diagnostic value that reproduces
	// the rendered text of the Go cause the failure was built from. The cause
	// chain stays local; it is never copied onto the wire.
	ErrCausalLeak = errors.New("structured error would carry its cause onto the wire")
)

// detailKeyPattern is the Section 15.1 constraint on detail keys, verbatim:
// "0-64 keys matching [a-z][a-z0-9_]{0,63}".
var detailKeyPattern = regexp.MustCompile(`^[a-z][a-z0-9_]{0,63}$`)

const (
	maxDetailKeys      = 64
	maxDetailDepth     = 4
	maxDetailCanonical = 16 * 1024
	minRedactableCause = 8
	maxMessageRunes    = 4096
	minMessageRunes    = 1
)

// excludedDetailKeys is the best-effort scanner Section 16.2 says an
// implementation SHOULD offer. It refuses a detail key that names one of the
// four classes Section 15.1 forbids outright — "No detail may contain a
// credential, raw transcript, environment secret, or opaque bundle content" —
// and nothing else.
//
// Matching is exact, never by substring, and that is deliberate. A substring
// rule refusing every key containing "token", "socket" or "credential" would
// refuse "token_count", "socket_timeout_ms" and "credential_profile" — ordinary
// diagnostics the specification admits — while still passing a secret written
// under an innocuous name. That is pure false-positive surface with no
// true-positive capability, and it is the exact defect removed from the
// Configuration extension-key validator: where the pinned document is silent
// about a name, be permissive.
//
// The list is also scoped to Section 15.1's four classes rather than to the
// whole Section 16.2 exclusion table. Section 16.2 governs manifests and
// bundles generated by ax; a diagnostic key naming a PID, a tmux socket or a
// Terminal Instance Binding is not a credential, a transcript, an environment
// secret, or bundle content, and refusing it here would invent a constraint the
// error contract does not state.
var excludedDetailKeys = map[string]string{
	// Credential.
	"access_token":       "credential",
	"api_key":            "credential",
	"auth_json":          "credential",
	"cookie":             "credential",
	"cookies":            "credential",
	"credential":         "credential",
	"credentials":        "credential",
	"oauth_token":        "credential",
	"passphrase":         "credential",
	"password":           "credential",
	"private_key":        "credential",
	"refresh_token":      "credential",
	"session_token":      "credential",
	"ssh_private_key":    "credential",
	"subscription_token": "credential",
	// Raw transcript.
	"raw_transcript":      "raw transcript",
	"scrollback":          "raw transcript",
	"terminal_scrollback": "raw transcript",
	"transcript":          "raw transcript",
	// Environment secret.
	"dotenv":             "environment secret",
	"env_secret":         "environment secret",
	"environment_secret": "environment secret",
	"secret":             "environment secret",
	"secrets":            "environment secret",
	// Opaque bundle content.
	"bundle_bytes":   "opaque bundle content",
	"bundle_content": "opaque bundle content",
	"opaque_bundle":  "opaque bundle content",
}

// RedactionBound states what the gates below can and cannot decide. It is
// quoted in README.md and asserted by this package's tests so that no caller
// reads a refusal as a confidentiality guarantee. Section 16.2 is explicit:
// "v0.5.0 does not claim reliable content-level secret scrubbing", and this
// implementation claims no more than the pinned document does.
const RedactionBound = "Detail redaction decides two things: whether a key exactly names one of the four classes " +
	"Section 15.1 forbids, and whether human text or a diagnostic value reproduces the rendered local cause " +
	"verbatim. It inspects no free-form value for secret content, matches no key by substring, and admits a " +
	"secret written under an innocuously named key. Section 16.2 does not claim content-level scrubbing and " +
	"neither does this package."

// ValidateDetails checks a diagnostic map against every Section 15.1 bound: the
// key count, the key grammar, the value nesting depth, the canonical byte size,
// and the four Section 15.1 detail classes that an exact key name makes decidable.
//
// The nesting bound counts containers opened by a detail value, matching the
// extension-value convention already used for canonical records: a value may
// open four containers and the fifth is refused.
func ValidateDetails(details Details) error {
	if details == nil {
		return fmt.Errorf("%w: details is required and must not be null", ErrInvalidDetails)
	}
	if len(details) > maxDetailKeys {
		return fmt.Errorf("%w: %d keys exceed the maximum of %d", ErrInvalidDetails, len(details), maxDetailKeys)
	}
	for _, key := range sortedKeys(details) {
		if !detailKeyPattern.MatchString(key) {
			return fmt.Errorf("%w: key %q does not match [a-z][a-z0-9_]{0,63}", ErrInvalidDetails, key)
		}
		if err := refuseExcludedKey(key); err != nil {
			return err
		}
		if err := validateDetailValue(key, details[key], 0); err != nil {
			return err
		}
	}
	measured, err := canonicaljson.CanonicalByteLength(map[string]any(details))
	if err != nil {
		return fmt.Errorf("%w: measure canonical details: %v", ErrInvalidDetails, err)
	}
	if measured > maxDetailCanonical {
		return fmt.Errorf(
			"%w: canonical details are %d bytes, maximum is %d", ErrInvalidDetails, measured, maxDetailCanonical)
	}
	return nil
}

func refuseExcludedKey(key string) error {
	if class, excluded := excludedDetailKeys[key]; excluded {
		return fmt.Errorf("%w: key %q names %s, which no detail may contain", ErrInvalidDetails, key, class)
	}
	return nil
}

func validateDetailValue(key string, value any, depth int) error {
	switch typed := value.(type) {
	case nil, bool, json.Number:
		return nil
	case string:
		if !utf8.ValidString(typed) {
			return fmt.Errorf("%w: details[%q] contains invalid UTF-8", ErrInvalidDetails, key)
		}
		return nil
	case []any:
		if depth == maxDetailDepth {
			return fmt.Errorf("%w: details[%q] exceeds maximum nesting depth %d", ErrInvalidDetails, key, maxDetailDepth)
		}
		for _, member := range typed {
			if err := validateDetailValue(key, member, depth+1); err != nil {
				return err
			}
		}
		return nil
	case map[string]any:
		if depth == maxDetailDepth {
			return fmt.Errorf("%w: details[%q] exceeds maximum nesting depth %d", ErrInvalidDetails, key, maxDetailDepth)
		}
		for _, nested := range sortedKeys(typed) {
			if !utf8.ValidString(nested) {
				return fmt.Errorf("%w: details[%q] has an object key that is not valid UTF-8", ErrInvalidDetails, key)
			}
			if err := refuseExcludedKey(nested); err != nil {
				return err
			}
			if err := validateDetailValue(key, typed[nested], depth+1); err != nil {
				return err
			}
		}
		return nil
	default:
		return fmt.Errorf("%w: details[%q] uses unsupported JSON type %T", ErrInvalidDetails, key, value)
	}
}

// refuseCausalLeak refuses human text or diagnostic values that reproduce the
// rendered text of the local cause verbatim. It exists because the ordinary way
// to lose a secret is fmt.Errorf("...: %v", err) on a cause that wrapped a
// command line, a transport payload, or a provider's stderr.
//
// What it decides is narrow and stated: verbatim containment of the whole
// rendered cause, and of each of its wrapped links. A paraphrase, a truncation,
// or a single extracted field of the cause is not detected. Causes shorter than
// minRedactableCause characters are skipped, because a cause rendering as
// "EOF" would otherwise refuse every message containing that substring.
func refuseCausalLeak(message string, details Details, cause error) error {
	for _, rendered := range causeChainText(cause) {
		if utf8.RuneCountInString(rendered) < minRedactableCause {
			continue
		}
		if strings.Contains(message, rendered) {
			return fmt.Errorf("%w: message reproduces the local cause verbatim", ErrCausalLeak)
		}
		for _, key := range sortedKeys(details) {
			if valueContains(details[key], rendered) {
				return fmt.Errorf("%w: details[%q] reproduces the local cause verbatim", ErrCausalLeak, key)
			}
		}
	}
	return nil
}

// causeChainText renders every link of the cause chain. Checking only the
// outermost rendering would miss a message that copied the innermost wrapped
// error, which is the link most likely to hold the untrusted text.
func causeChainText(cause error) []string {
	var rendered []string
	for current := cause; current != nil; {
		rendered = append(rendered, current.Error())
		switch unwrapped := current.(type) {
		case interface{ Unwrap() error }:
			current = unwrapped.Unwrap()
		case interface{ Unwrap() []error }:
			for _, joined := range unwrapped.Unwrap() {
				rendered = append(rendered, causeChainText(joined)...)
			}
			current = nil
		default:
			current = nil
		}
	}
	return rendered
}

func valueContains(value any, needle string) bool {
	switch typed := value.(type) {
	case string:
		return strings.Contains(typed, needle)
	case []any:
		for _, member := range typed {
			if valueContains(member, needle) {
				return true
			}
		}
	case map[string]any:
		for _, member := range typed {
			if valueContains(member, needle) {
				return true
			}
		}
	}
	return false
}

func sortedKeys[Value any](source map[string]Value) []string {
	keys := make([]string, 0, len(source))
	for key := range source {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}

// RealmEvidence is the exact typed detail set Section 15.3 requires when
// broker, tmux server generation, or functional-sentinel evidence is missing or
// unsafe: "capability_unavailable with typed details containing capability,
// caller_realm, broker_state, tmux_server_generation, and remediation".
//
// tmux_server_generation is carried here on that clause's explicit instruction.
// The Section 16.2 exclusion of backend generations governs manifests and
// bundles generated by ax, and the more specific clause licenses this one
// diagnostic field.
type RealmEvidence struct {
	Capability           string
	CallerRealm          string
	BrokerState          string
	TmuxServerGeneration string
	Remediation          string
}

// Details renders the typed set. Every field is required, because a caller that
// omits one has not produced the typed details the clause names.
func (evidence RealmEvidence) Details() (Details, error) {
	return requiredTypedDetails(map[string]string{
		"capability":             evidence.Capability,
		"caller_realm":           evidence.CallerRealm,
		"broker_state":           evidence.BrokerState,
		"tmux_server_generation": evidence.TmuxServerGeneration,
		"remediation":            evidence.Remediation,
	})
}

// TargetAuth is the exact typed detail set Section 15.3 requires for
// target_auth_missing: "typed provider_id, provider_build, macos_version,
// tmux_server_generation, and remediation".
type TargetAuth struct {
	ProviderID           string
	ProviderBuild        string
	MacOSVersion         string
	TmuxServerGeneration string
	Remediation          string
}

// Details renders the typed set. Every field is required.
func (target TargetAuth) Details() (Details, error) {
	return requiredTypedDetails(map[string]string{
		"provider_id":            target.ProviderID,
		"provider_build":         target.ProviderBuild,
		"macos_version":          target.MacOSVersion,
		"tmux_server_generation": target.TmuxServerGeneration,
		"remediation":            target.Remediation,
	})
}

// targetAuthMissingKeys is the presence requirement New enforces for
// target_auth_missing, so the generic constructor cannot emit that code with a
// weaker detail set than the typed constructor produces.
var targetAuthMissingKeys = []string{
	"macos_version",
	"provider_build",
	"provider_id",
	"remediation",
	"tmux_server_generation",
}

func requiredTypedDetails(fields map[string]string) (Details, error) {
	details := make(Details, len(fields))
	for _, key := range sortedKeys(fields) {
		if fields[key] == "" {
			return nil, fmt.Errorf("%w: typed detail %q is required and must not be empty", ErrInvalidDetails, key)
		}
		details[key] = fields[key]
	}
	if err := ValidateDetails(details); err != nil {
		return nil, err
	}
	return details, nil
}

func requireDetailKeys(code Code, details Details, required []string) error {
	for _, key := range required {
		value, present := details[key]
		if !present {
			return fmt.Errorf("%w: %q requires typed detail %q", ErrInvalidDetails, code, key)
		}
		text, ok := value.(string)
		if !ok || text == "" {
			return fmt.Errorf("%w: %q requires a non-empty typed detail %q", ErrInvalidDetails, code, key)
		}
	}
	return nil
}
